"""Bundled VARIANT-1 model-provider profiles.

Most providers speak the OpenAI chat-completions protocol, so breadth is data
rather than duplicated transport code. Anthropic and Gemini retain dedicated
wire adapters in ``LLMRouter``.
"""

from __future__ import annotations
from copy import deepcopy

from .base import ProviderProfile


# Capabilities, not task/model special cases in the transport. Exact named
# families are intentional: future/custom models must declare their own floor.
# Sources: official model pages and native thinking guides (review E66).
_OPENAI_REASONING_RULES = (
    {"patterns": ("gpt-5.6-luna*",),
     "efforts": ("none", "low", "medium", "high", "xhigh", "max")},
    {"patterns": ("gpt-5.5", "gpt-5.5-20*", "gpt-5.4", "gpt-5.4-20*", "gpt-5.4-mini*"),
     "efforts": ("none", "low", "medium", "high", "xhigh")},
    {"patterns": ("gpt-6-astra*", "gpt-5.3-codex-spark*"),
     "efforts": ("low", "medium", "high", "xhigh")},
    {"patterns": ("o1", "o1-20*", "o3", "o3-20*", "o3-mini*", "o4-mini*"),
     "efforts": ("low", "medium", "high")},
)
_ANTHROPIC_REASONING_RULES = (
    {"patterns": ("claude-mythos*", "claude-fable-5*"),
     "minimum_fields": {"thinking": {"type": "adaptive"}, "output_config.effort": "low"}},
    {"patterns": ("claude-opus-5*", "claude-sonnet-5*"),
     "minimum_fields": {"thinking": {"type": "disabled"}, "output_config.effort": "low"}},
    {"patterns": ("claude-*-4*", "claude-3-7*"),
     "minimum_fields": {"thinking": {"type": "disabled"}}},
)
_GEMINI_REASONING_RULES = (
    {"patterns": ("gemini-2.5-flash*",),
     "minimum_fields": {"generationConfig.thinkingConfig": {"thinkingBudget": 0}}},
    {"patterns": ("gemini-2.5-pro*",),
     "minimum_fields": {"generationConfig.thinkingConfig": {"thinkingBudget": 128}}},
    {"patterns": ("gemini-3-flash*", "gemini-3.[156]-flash*"),
     "minimum_fields": {"generationConfig.thinkingConfig": {"thinkingLevel": "minimal"}}},
    {"patterns": ("gemini-3-pro*", "gemini-3.1-pro*", "gemini-3.[78]-flash*"),
     "minimum_fields": {"generationConfig.thinkingConfig": {"thinkingLevel": "low"}}},
)


def _o(name: str, display: str, base: str, env: tuple[str, ...], model: str,
       *, aliases: tuple[str, ...] = (), description: str = "",
       signup: str = "", reasoning: bool = False, auth: str = "bearer",
       models_url: str = "", fallback: tuple[str, ...] = (),
       headers: dict[str, str] | None = None,
       defaults: dict | None = None, omit_temperature: bool = False,
       reasoning_efforts: tuple[str, ...] = (),
       reasoning_effort_field: str = "",
       reasoning_model_rules: tuple[dict, ...] = (),
       vision: bool = False, prompt_cache_body_field: str = "",
       prompt_cache_header: str = "", sampling_fields: tuple[str, ...] = (
           "temperature",
       ), completion_token_field: str = "max_tokens",
       max_completion_patterns: tuple[str, ...] = (),
       sampling_forbidden_patterns: tuple[str, ...] = ()) -> ProviderProfile:
    return ProviderProfile(
        name=name, display_name=display, aliases=aliases, base_url=base,
        models_url=models_url, env_vars=env, auth_style=auth,
        default_model=model, fallback_models=fallback,
        supports_vision=vision, supports_reasoning=reasoning,
        reasoning_efforts=reasoning_efforts,
        reasoning_effort_field=reasoning_effort_field,
        reasoning_model_rules=deepcopy(reasoning_model_rules),
        description=description,
        signup_url=signup, default_headers=headers or {},
        request_defaults=defaults or {}, omit_temperature=omit_temperature,
        sampling_fields=(() if omit_temperature else sampling_fields),
        completion_token_field=completion_token_field,
        max_completion_token_model_patterns=max_completion_patterns,
        sampling_forbidden_model_patterns=sampling_forbidden_patterns,
        prompt_cache_body_field=prompt_cache_body_field,
        prompt_cache_header=prompt_cache_header,
    )


def builtin_profiles() -> list[ProviderProfile]:
    """Return fresh profile objects so registries remain test-isolated."""
    return [
        ProviderProfile(
            name="anthropic", display_name="Anthropic", api_style="anthropic",
            aliases=("claude",), base_url="https://api.anthropic.com",
            env_vars=("ANTHROPIC_API_KEY",), auth_style="x-api-key",
            default_model="claude-sonnet-4-6", supports_vision=True,
            supports_reasoning=True,
            reasoning_model_rules=deepcopy(_ANTHROPIC_REASONING_RULES),
            signup_url="https://console.anthropic.com/",
            description="Claude models through the native Messages API.",
            sampling_fields=("temperature",),
            sampling_forbidden_model_patterns=(
                "claude-opus-4-7*", "claude-opus-4-8*", "claude-*-5*",
                "claude-mythos*",
            ),
            structured_output_style="anthropic_json_schema",
        ),
        _o("openai", "OpenAI", "https://api.openai.com/v1", ("OPENAI_API_KEY",),
           "gpt-4o", aliases=("gpt",), reasoning=True, vision=True,
           reasoning_effort_field="reasoning_effort",
           reasoning_model_rules=_OPENAI_REASONING_RULES,
           sampling_fields=("temperature", "top_p"),
           completion_token_field="auto",
           max_completion_patterns=("gpt-5*", "o1*", "o3*", "o4*"),
           sampling_forbidden_patterns=("gpt-5*", "o1*", "o3*", "o4*"),
           signup="https://platform.openai.com/",
           description="OpenAI chat-completions models."),
        _o(
            "openai-codex",
            "OpenAI Codex (ChatGPT OAuth)",
            "https://chatgpt.com/backend-api/codex",
            (),
            "gpt-5.3-codex-spark",
            aliases=("codex-oauth", "chatgpt-codex"),
            reasoning=True,
            vision=True,
            models_url=(
                "https://chatgpt.com/backend-api/codex/models?client_version=1.0.0"
            ),
            omit_temperature=True,
            reasoning_efforts=("low", "medium", "high", "xhigh", "max"),
            reasoning_model_rules=_OPENAI_REASONING_RULES,
            prompt_cache_body_field="prompt_cache_key",
            prompt_cache_header="session_id",
            signup="https://chatgpt.com/",
            description=(
                "ChatGPT subscription inference over the Codex Responses wire. "
                "VARIANT-1 keeps ownership of context, tools, and the agent loop."
            ),
        ),
        _o("xai", "xAI", "https://api.x.ai/v1", ("XAI_API_KEY",),
           "grok-4.3", aliases=("grok", "x.ai"), reasoning=True, vision=True,
           reasoning_efforts=("low", "medium", "high"),
           reasoning_effort_field="reasoning_effort",
           sampling_fields=("temperature", "top_p"),
           prompt_cache_header="x-grok-conv-id",
           signup="https://console.x.ai/", description="Grok models through xAI."),
        _o("nvidia", "NVIDIA NIM", "https://integrate.api.nvidia.com/v1",
           ("NVIDIA_API_KEY",), "nvidia/nemotron-3-ultra-550b-a55b",
           aliases=("nim", "nvidia-nim"), reasoning=True,
           reasoning_model_rules=({"patterns": ("*",), "minimum_fields": {
               "chat_template_kwargs.enable_thinking": False, "reasoning_budget": 0,
           }},),
           sampling_fields=("temperature", "top_p"),
           signup="https://build.nvidia.com/", description="NVIDIA-hosted NIM models."),
        ProviderProfile(
            name="gemini", display_name="Google Gemini", api_style="gemini",
            aliases=("google", "google-gemini"),
            base_url="https://generativelanguage.googleapis.com/v1beta",
            env_vars=("GEMINI_API_KEY", "GOOGLE_API_KEY"), auth_style="query",
            default_model="gemini-2.0-flash", supports_vision=True, supports_reasoning=True,
            reasoning_model_rules=deepcopy(_GEMINI_REASONING_RULES),
            signup_url="https://aistudio.google.com/",
            description="Gemini through the Generative Language API.",
        ),
        ProviderProfile(
            name="google-antigravity", display_name="Google AI subscription", api_style="gemini",
            aliases=("google-ai", "antigravity"),
            base_url="https://daily-cloudcode-pa.googleapis.com", auth_style="bearer",
            supports_vision=True, supports_reasoning=True,
            reasoning_model_rules=deepcopy(_GEMINI_REASONING_RULES),
            signup_url="https://antigravity.google/",
            description="Google AI subscription access through Antigravity OAuth. VARIANT-1 owns the Python tools and agent loop.",
        ),
        _o("openrouter", "OpenRouter", "https://openrouter.ai/api/v1",
           ("OPENROUTER_API_KEY",), "openai/gpt-4o-mini", aliases=("or",),
           models_url="https://openrouter.ai/api/v1/models", reasoning=True,
           reasoning_efforts=("low", "medium", "high"),
           reasoning_effort_field="reasoning.effort",
           reasoning_model_rules=tuple({**rule, "patterns": tuple(
               "openai/" + pattern for pattern in rule["patterns"]
           )} for rule in _OPENAI_REASONING_RULES),
           vision=True,
           signup="https://openrouter.ai/", description="Multi-provider model router.",
           headers={"HTTP-Referer": "https://variant1.local", "X-Title": "VARIANT-1"}),
        _o("deepseek", "DeepSeek", "https://api.deepseek.com/v1",
           ("DEEPSEEK_API_KEY",), "deepseek-chat", reasoning=True,
           fallback=("deepseek-chat", "deepseek-reasoner"),
           signup="https://platform.deepseek.com/"),
        _o("fireworks", "Fireworks AI", "https://api.fireworks.ai/inference/v1",
           ("FIREWORKS_API_KEY",), "", reasoning=True, vision=True,
           signup="https://app.fireworks.ai/settings/users/api-keys",
           description="Fireworks OpenAI-compatible inference."),
        _o("deepinfra", "DeepInfra", "https://api.deepinfra.com/v1/openai",
           ("DEEPINFRA_API_KEY",), "", reasoning=True, vision=True,
           signup="https://deepinfra.com/dash/api_keys",
           description="Open models through DeepInfra's compatible API."),
        _o("nebius-token-factory", "Nebius Token Factory",
           "https://api.tokenfactory.nebius.com/v1",
           ("NEBIUS_API_KEY", "NEBIUS_TOKEN_FACTORY_API_KEY"), "",
           models_url="https://api.tokenfactory.nebius.com/v1/models?verbose=true",
           reasoning=True, vision=True, signup="https://tokenfactory.nebius.com/",
           description="Nebius Token Factory inference."),
        _o("upstage", "Upstage Solar", "https://api.upstage.ai/v1",
           ("UPSTAGE_API_KEY",), "solar-pro4", reasoning=True,
           reasoning_efforts=("low", "medium", "high"),
           reasoning_effort_field="reasoning_effort",
           signup="https://console.upstage.ai/api-keys",
           description="Upstage Solar models."),
        _o("ai-gateway", "Vercel AI Gateway", "https://ai-gateway.vercel.sh/v1",
           ("AI_GATEWAY_API_KEY",), "", reasoning=True, vision=True,
           signup="https://vercel.com/ai-gateway",
           description="Multi-provider models through Vercel AI Gateway."),
        _o("tencent-tokenhub", "Tencent TokenHub",
           "https://tokenhub.tencentmaas.com/v1",
           ("TENCENT_TOKENHUB_API_KEY", "TOKENHUB_API_KEY"), "",
           signup="https://cloud.tencent.com/document/product/1823/130050",
           description="Tencent TokenHub OpenAI-compatible inference."),
        ProviderProfile(
            name="tencent-tokenplan", display_name="Tencent TokenPlan",
            api_style="anthropic",
            base_url="https://api.lkeap.cloud.tencent.com/plan/anthropic",
            env_vars=("TOKENPLAN_API_KEY",), auth_style="x-api-key",
            default_model="", supports_reasoning=True,
            description="Tencent TokenPlan through the Anthropic Messages wire.",
        ),
        _o("alibaba", "Alibaba DashScope", "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
           ("DASHSCOPE_API_KEY",), "qwen-plus", aliases=("dashscope", "qwen-dashscope"),
           signup="https://www.alibabacloud.com/product/model-studio"),
        _o("alibaba-cn", "Alibaba DashScope (China)",
           "https://dashscope.aliyuncs.com/compatible-mode/v1",
           ("DASHSCOPE_API_KEY",), "qwen-plus",
           signup="https://help.aliyun.com/zh/model-studio/"),
        _o("alibaba-token-plan", "Alibaba Token Plan",
           "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
           ("ALIBABA_TOKEN_PLAN_API_KEY",), "",
           signup="https://help.aliyun.com/zh/model-studio/"),
        _o("alibaba-token-plan-cn", "Alibaba Token Plan (China)",
           "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
           ("ALIBABA_TOKEN_PLAN_CN_API_KEY", "ALIBABA_TOKEN_PLAN_API_KEY"), "",
           signup="https://help.aliyun.com/zh/model-studio/"),
        _o("alibaba-coding-plan", "Alibaba Coding Plan", "https://coding-intl.dashscope.aliyuncs.com/v1",
           ("ALIBABA_CODING_PLAN_API_KEY", "DASHSCOPE_API_KEY"), "qwen3-coder-plus",
           aliases=("alibaba-coding", "dashscope-coding"), omit_temperature=True),
        _o("alibaba-coding-plan-cn", "Alibaba Coding Plan (China)",
           "https://coding.dashscope.aliyuncs.com/v1",
           ("ALIBABA_CODING_PLAN_CN_API_KEY", "ALIBABA_CODING_PLAN_API_KEY"),
           "qwen3-coder-plus", omit_temperature=True),
        _o("commandcode", "CommandCode", "https://api.commandcode.ai/provider/v1",
           ("COMMANDCODE_API_KEY",), "",
           models_url="https://api.commandcode.ai/provider/v1/models",
           reasoning=True, vision=True, signup="https://commandcode.ai/",
           description="CommandCode multi-model compatible API."),
        ProviderProfile(
            name="commandcode-anthropic", display_name="CommandCode (Anthropic)",
            api_style="anthropic", base_url="https://api.commandcode.ai/provider/v1",
            models_url="https://api.commandcode.ai/provider/v1/models",
            env_vars=("COMMANDCODE_API_KEY",), auth_style="x-api-key",
            default_model="", supports_vision=True, supports_reasoning=True,
            signup_url="https://commandcode.ai/",
            description="CommandCode models through the Anthropic Messages wire.",
        ),
        _o("arcee", "Arcee AI", "https://api.arcee.ai/api/v1", ("ARCEEAI_API_KEY",),
           "arcee-ai/trinity-large-preview", aliases=("arcee-ai",)),
        _o("azure-foundry", "Azure AI Foundry", "", ("AZURE_FOUNDRY_API_KEY",), "",
           aliases=("azure", "azure-ai-foundry"), description="User-configured Azure Foundry endpoint."),
        _o("copilot", "GitHub Copilot", "https://api.githubcopilot.com", ("GITHUB_TOKEN",),
           "gpt-4o", aliases=("github-copilot", "github-models"),
           vision=True,
           description="GitHub-hosted compatible inference; token and entitlement required."),
        _o("gmi", "GMI Cloud", "https://api.gmi-serving.com/v1", ("GMI_API_KEY",),
           "deepseek-ai/DeepSeek-V3.2", aliases=("gmi-cloud",)),
        _o("huggingface", "Hugging Face", "https://router.huggingface.co/v1", ("HF_TOKEN",),
           "openai/gpt-oss-120b", aliases=("hf", "hugging-face")),
        _o("kilocode", "Kilo Gateway", "https://api.kilo.ai/api/gateway", ("KILOCODE_API_KEY",),
           "anthropic/claude-sonnet-4-6", aliases=("kilo", "kilo-code"), vision=True),
        _o("kimi-coding", "Kimi Coding", "https://api.moonshot.ai/v1",
           ("KIMI_API_KEY", "KIMI_CODING_API_KEY"), "kimi-k2.5",
           aliases=("kimi", "moonshot"), reasoning=True, omit_temperature=True),
        _o("kimi-coding-cn", "Kimi / Moonshot (China)",
           "https://api.moonshot.cn/v1", ("KIMI_CN_API_KEY",), "kimi-k2.5",
           reasoning=True, omit_temperature=True),
        ProviderProfile(
            name="minimax", display_name="MiniMax", api_style="anthropic",
            aliases=("mini-max",), base_url="https://api.minimax.io/anthropic",
            env_vars=("MINIMAX_API_KEY",), auth_style="x-api-key",
            default_model="MiniMax-M2.5", supports_reasoning=True,
            description="MiniMax through its Anthropic-compatible API.",
        ),
        ProviderProfile(
            name="minimax-cn", display_name="MiniMax (China)",
            api_style="anthropic", base_url="https://api.minimaxi.com/anthropic",
            env_vars=("MINIMAX_CN_API_KEY",), auth_style="x-api-key",
            default_model="MiniMax-M2.5", supports_reasoning=True,
            description="MiniMax China through its Anthropic-compatible API.",
        ),
        ProviderProfile(
            name="minimax-oauth", display_name="MiniMax (OAuth)",
            api_style="anthropic", base_url="https://api.minimax.io/anthropic",
            env_vars=(), auth_style="x-api-key", default_model="MiniMax-M2.7",
            supports_reasoning=True, signup_url="https://api.minimax.io/",
            description="MiniMax subscription via its user-code/PKCE OAuth flow.",
        ),
        ProviderProfile(
            name="minimax-oauth-cn", display_name="MiniMax China (OAuth)",
            api_style="anthropic", base_url="https://api.minimaxi.com/anthropic",
            env_vars=(), auth_style="x-api-key", default_model="MiniMax-M2.7",
            supports_reasoning=True, signup_url="https://api.minimaxi.com/",
            description="MiniMax China subscription via user-code/PKCE OAuth.",
        ),
        _o("nous", "Nous Portal", "https://inference.nousresearch.com/v1", ("NOUS_API_KEY",),
           "Hermes-4-405B", aliases=("nous-portal", "nousresearch")),
        _o(
            "hermes", "Hermes Agent (Nous OAuth)", "http://127.0.0.1:8645/v1",
            (), "upstage/solar-pro4:free", aliases=("hermes-agent", "hermes-nous"),
            auth="optional", reasoning=True, vision=True,
            reasoning_efforts=("minimal", "low", "medium", "high", "xhigh", "max"),
            reasoning_effort_field="reasoning_effort",
            description=(
                "Signed-in Nous Portal inference through Hermes Agent's fixed "
                "loopback OAuth proxy; VARIANT-1 never receives the OAuth bearer."
            ),
        ),
        _o("novita", "Novita AI", "https://api.novita.ai/openai/v1", ("NOVITA_API_KEY",),
           "deepseek/deepseek-v3.2", aliases=("novita-ai",)),
        _o(
            "opencode-zen", "OpenCode Zen", "https://opencode.ai/zen/v1",
            ("OPENCODE_API_KEY", "OPENCODE_ZEN_API_KEY"),
            "x-preview-f-free",
            aliases=("opencode", "zen"),
            auth="optional",
            reasoning=True,
            vision=True,
            models_url="https://opencode.ai/zen/v1/models",
            fallback=(
                "big-pickle",
                "deepseek-v4-flash-free",
                "mimo-v2.5-free",
                "nemotron-3-ultra-free",
                "nemotron-3.5-lightning-free",
                "laguna-s-2.1-free",
                "muse-spark-1.2-contributor-free",
                "hy3-free",
            ),
            description=(
                "OpenCode Zen's OpenAI-compatible route. Explicit free model IDs "
                "work anonymously; an optional OpenCode API key may unlock account "
                "models."
            ),
        ),
        _o("opencode-go", "OpenCode Go", "https://opencode.ai/zen/go/v1",
           ("OPENCODE_GO_API_KEY",), "", reasoning=True, vision=True,
           description="OpenCode Go compatible inference."),
        _o("opencode-free", "OpenCode Free", "https://opencode.ai/zen/v1",
           (), "big-pickle", auth="optional", reasoning=True, vision=True,
           models_url="https://opencode.ai/zen/v1/models",
           description="OpenCode's keyless free-model route."),
        _o("qwen", "Qwen Portal", "https://portal.qwen.ai/v1", ("QWEN_API_KEY",),
           "qwen3-coder-plus", aliases=("qwen-portal",)),
        _o("stepfun", "StepFun", "https://api.stepfun.ai/step_plan/v1", ("STEPFUN_API_KEY",),
           "step-3.5-flash", aliases=("step",)),
        _o("xiaomi", "Xiaomi MiMo", "https://api.xiaomimimo.com/v1", ("XIAOMI_API_KEY",),
           "mimo-v2-flash", aliases=("mimo", "xiaomi-mimo"), reasoning=True),
        _o("zai", "Z.AI", "https://api.z.ai/api/paas/v4", ("ZAI_API_KEY", "GLM_API_KEY"),
           "glm-5", aliases=("glm", "z.ai", "zhipu"), reasoning=True),
        _o(
            "ollama", "Ollama Desktop Cloud", "http://127.0.0.1:11434/v1", (),
            "gemma4:31b-cloud", auth="optional", reasoning=True, vision=True,
            reasoning_efforts=("low", "medium", "high", "max"),
            reasoning_effort_field="reasoning_effort",
            description=(
                "Signed-in Ollama Desktop Cloud subscription through the fixed "
                "loopback helper; only *:cloud and *-cloud tags are accepted."
            ),
        ),
        _o("lmstudio", "LM Studio", "http://127.0.0.1:1234/v1", (), "local-model",
           aliases=("lm-studio",), auth="optional", description="Local LM Studio server."),
    ]
