"""Typed runtime services installed once on :class:`app_host.AppHost`.

The runtime is a late-bound composition boundary because many VARIANT-1 services
refer back to ports built by ``AppHost``.  It is deliberately *not* a callback
registry: each field is a concrete service implementing an explicit protocol
with stable method signatures.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Protocol, runtime_checkable


StopPredicate = Callable[[], bool]


@runtime_checkable
class ChatRuntime(Protocol):
    async def handle_chat(
        self, websocket: Any, text: str, session: Any, *, resume: bool = False,
        reserved: bool = False, client_id: str = "", source: str = "",
        images: list[dict] | None = None, attachment_text: str = "",
    ) -> None: ...
    def build_task_turn_ports(self, websocket: Any, session: Any) -> Any: ...
    async def extract_and_store(
        self, user_text: str, reply: str, *, evidence: dict | None = None,
    ) -> None: ...
    async def remember_explicit(
        self, text: str, *, session_id: str = "",
    ) -> bool: ...
    async def compress_messages(
        self, messages: list, protect_first: int = 2, protect_last: int = 6,
        should_stop: StopPredicate | None = None,
    ) -> list: ...
    def approx_tokens(self, messages: list) -> int: ...
    def ctx_compress_threshold(self) -> int: ...
    async def count_prompt_tokens(
        self, messages: list, *, tools: list | None = None, image_b64=None,
    ) -> int | None: ...
    def prompt_context(
        self, memories: list, attachment_context: str = "",
    ) -> Any: ...
    def vision_state(self) -> tuple[bool, str]: ...
    def build_system_prompt(
        self, memories: list, attachment_context: str = "",
    ) -> str: ...
    def build_internal_system_prompt(
        self, memories: list, attachment_context: str = "",
    ) -> str: ...
    def snapshot_resume_state(self, chat_id: str = "") -> tuple[Any, str]: ...
    def snapshot_follow_up_state(self, chat_id: str = "") -> tuple[Any, str]: ...
    async def accept_follow_up_evidence(self, chat_id: str, candidate: Any) -> Any: ...
    def orphaned_task_payload(self, chat_id: str = '') -> dict | None: ...
    def sessions_message(self) -> dict: ...
    def viewed_session_id(self, session: Any) -> str: ...
    async def run_task(
        self, websocket: Any, text: str, session: Any, *, resume: bool = False,
        turn_seq: Any = None, client_id: str = "", source: str = "",
        images: list[dict] | None = None, attachment_text: str = "",
        runtime_admission_id: str = "", ticket_id: str = "",
    ) -> None: ...


@runtime_checkable
class MemoryRuntime(Protocol):
    store: Any
    def profile_items(self) -> list: ...
    async def consolidate_once(self) -> int: ...


@runtime_checkable
class ModelRuntime(Protocol):
    def vision_config(self) -> dict: ...
    def vision_state(self) -> tuple[bool, str]: ...
    def config_status(self) -> dict: ...
    def doctor_snapshot(self) -> dict: ...
    def scan_models(self) -> list: ...
    async def restart_engine(
        self, model_path: str, mmproj_path: str = "", *,
        should_apply: StopPredicate | None = None,
    ) -> Any: ...
    async def restart_engine_keep_model(self) -> Any: ...
    async def reconcile_local_engine(self) -> Any: ...


@runtime_checkable
class VoiceRuntime(Protocol):
    def config(self) -> dict: ...
    def stt_route(self) -> str: ...
    def stt_provider(self) -> str: ...
    def route(self) -> str: ...
    def provider(self) -> str: ...
    def voice(self) -> str: ...
    def available(self) -> bool: ...
    def mime_type(self) -> str: ...
    def catalog(self) -> dict: ...
    async def list_voices(self) -> list[dict]: ...
    async def synthesize(
        self, text: str, speed: float | None = None, voice: str = "",
    ) -> bytes: ...
    async def transcribe_audio(
        self, wav: bytes, language: str | None = None,
    ) -> str: ...
    async def transcribe_task(
        self, websocket: Any, session: Any, wav: bytes,
        language: str | None,
    ) -> None: ...
    def set_config(self, key: str, value: Any) -> None: ...


@runtime_checkable
class WorkflowRuntime(Protocol):
    async def notify_proactive(
        self, mood: str, text: str, *, source: str = "", title: str = "",
        meta: dict | None = None,
    ) -> None: ...
    async def run_automation(
        self, task: dict, payload: str = "", trigger_source: str = "trigger",
    ) -> str: ...
    def prior_incomplete_automation_run(self, run_id: str) -> Any: ...
    async def automation_loop(self) -> None: ...


@runtime_checkable
class ToolRuntime(Protocol):
    def state(self) -> dict: ...


@runtime_checkable
class ToolRegistryRuntime(Protocol):
    """Internal handler registry behind the immutable ASTB catalog."""

    def register(self, tool: Any) -> None: ...
    def get(self, name: str) -> Any: ...
    def get_capability(self, capability_id: str) -> Any: ...
    def all(self) -> list[Any]: ...


@runtime_checkable
class CapabilityBrokerRuntime(Protocol):
    """The sole admission and receipt boundary for model-caused effects."""

    async def invoke_name(self, name: str, args: Any, context: Any) -> Any: ...
    def context_for_provider(self, **fields: Any) -> Any: ...
    def reserve_provider_outer_call(self, **fields: Any) -> dict[str, Any]: ...
    def finish_provider_outer_call(self, reservation: Any, outcome: Any) -> None: ...
    def register_receipt_sink(self, sink: Callable[[Any], Any]) -> None: ...


@runtime_checkable
class CatalogRuntime(Protocol):
    mutation: Any
    mutation_authority: Any
    repository: Any
    children: Any

    def reconcile_registry(self, *, require_complete: bool = False) -> Any: ...
    def select(self, chat_id: str, category_id: str) -> dict[str, Any]: ...
    def runtime_prompt(self, chat_id: str, query: str = "") -> str: ...
    def reset(self, chat_id: str) -> dict[str, Any]: ...


@runtime_checkable
class SessionRuntimeRegistryRuntime(Protocol):
    repository: Any

    def ensure_runtime(self, chat_id: str) -> Any: ...
    def reconcile_runtime_owners(self, chat_ids: list[str]) -> Any: ...
    def register_chat_cleanup(self, callback: Callable[[str], Any]) -> None: ...
    def try_reserve_run(self, chat_id: str, **fields: Any) -> Any: ...
    async def reserve_run(self, chat_id: str, **fields: Any) -> Any: ...
    def begin_run(self, admission_id: str, **fields: Any) -> Any: ...
    def finish_run(self, admission_id: str, **fields: Any) -> Any: ...


@runtime_checkable
class KernelRuntime(Protocol):
    worker_executable: str

    async def execute(self, **fields: Any) -> Any: ...
    async def close_chat(self, chat_id: str, **fields: Any) -> Any: ...


@runtime_checkable
class ActionRuntime(Protocol):
    async def run_interactive(
        self, websocket: Any, actions: list, should_stop: StopPredicate | None = None,
    ) -> Any: ...
    async def run_headless(
        self, actions: list, should_stop: StopPredicate | None = None,
    ) -> Any: ...


@runtime_checkable
class WorkRuntime(Protocol):
    """Process-owned durable work service lifecycle.

    Domain-specific APIs remain on the concrete service facets.  Host
    composition depends only on lifecycle so the Work Fabric can evolve
    without turning ``HostRuntime`` into a callback registry.
    """

    async def start(self) -> None: ...
    async def shutdown(self) -> None: ...
    def record_capability_receipt(self, receipt: Any) -> None: ...


@runtime_checkable
class ChatSessionRuntime(Protocol):
    """Durable chat transcript, per-chat settings, compaction, and search."""

    def list_sessions(self) -> list[dict[str, Any]]: ...
    def get_active(self) -> str: ...


@runtime_checkable
class ExecutionHostRuntime(Protocol):
    """Durable multi-terminal and structured-process runtime."""

    terminals: Any
    processes: Any
    recovery_report: Any

    def events(self, **filters: Any) -> Any: ...
    def capability_report(self) -> dict[str, Any]: ...
    def shutdown(self) -> None: ...


@runtime_checkable
class CodingRuntime(Protocol):
    """Repository discovery, managed-worktree, Review, and check runtime."""

    repository: Any
    process: Any
    repositories: Any
    worktrees: Any
    review: Any
    checks: Any

    def startup(self) -> dict[str, Any]: ...
    def shutdown(self) -> None: ...
    def health(self) -> dict[str, Any]: ...


@runtime_checkable
class GoalRuntime(Protocol):
    """Durable objective DAG and deterministic supervisor service."""

    supervisor: Any

    def create(self, **fields: Any) -> Any: ...
    def get(self, goal_id: str) -> Any: ...
    def list(self, **filters: Any) -> Any: ...
    def snapshot(self, goal_id: str) -> dict[str, Any]: ...


@runtime_checkable
class PeerRuntime(Protocol):
    async def start(self) -> None: ...
    async def shutdown(self) -> None: ...
    def list_peers(self, kind: str = "", status: str = "", limit: int = 100) -> list[dict[str, Any]]: ...
    def get_peer(self, peer_id: str) -> dict[str, Any]: ...


@runtime_checkable
class ArtifactAuthoringRuntime(Protocol):
    """Versioned source specifications, renders, validation, and publication."""

    repository: Any

    def create(self, **fields: Any) -> Any: ...
    def revise(self, artifact_id: str, specification: Any, **options: Any) -> Any: ...
    def snapshot(self, artifact_id: str, revision: int | None = None) -> Any: ...
    def publish(self, artifact_id: str, formats: Any, **options: Any) -> Any: ...
    def state(self) -> dict[str, Any]: ...


@runtime_checkable
class BrowserFabricRuntime(Protocol):
    """Durable multi-profile browser sessions and guarded page references."""

    async def open_session(self, **options: Any) -> Any: ...
    async def shutdown(self) -> None: ...
    def sessions(self, **filters: Any) -> Any: ...
    def capability_matrix(self) -> dict[str, Any]: ...


@runtime_checkable
class DesktopFabricRuntime(Protocol):
    """Durable Windows app/window catalog, observation, and action evidence."""

    def refresh_catalog(self) -> Any: ...
    def apps(self, **filters: Any) -> Any: ...
    def windows(self, **filters: Any) -> Any: ...
    def capability_report(self) -> dict[str, Any]: ...
    def close(self) -> None: ...


@runtime_checkable
class ExtensionRuntime(Protocol):
    """Executable extension packages and full MCP lifecycle."""

    packages: Any
    skills: Any
    mcp: Any

    async def start(self) -> dict[str, Any]: ...
    async def shutdown(self) -> None: ...
    def state(self) -> dict[str, Any]: ...
    def rescan(self) -> dict[str, Any]: ...
    def plugins(self, query: str = "", *, limit: int = 500) -> list[dict[str, Any]]: ...
    def set_enabled(self, package_id: str, enabled: bool) -> dict[str, Any]: ...


@runtime_checkable
class LifecycleRuntime(Protocol):
    async def start_critical_services(self) -> None: ...
    async def start_optional_services(self) -> None: ...
    async def automation_loop(self) -> None: ...
    async def consolidation_loop(self) -> None: ...
    def dev_reset_on_launch(self) -> None: ...
    async def check_orphaned_task(self) -> None: ...
    def detect_hardware(self) -> dict: ...
    async def start_workers(self) -> list: ...
    async def shutdown(self) -> None: ...


@dataclass(frozen=True)
class HostRuntime:
    chat: ChatRuntime
    memory: MemoryRuntime
    models: ModelRuntime
    voice: VoiceRuntime
    workflows: WorkflowRuntime
    tool_settings: ToolRuntime
    registry: ToolRegistryRuntime
    broker: CapabilityBrokerRuntime
    catalog: CatalogRuntime
    catalog_releases: Any
    session_control: Any
    session_runtimes: SessionRuntimeRegistryRuntime
    kernel: KernelRuntime
    actions: ActionRuntime
    session_artifacts: Any
    work: WorkRuntime
    sessions: ChatSessionRuntime
    execution: ExecutionHostRuntime
    coding: CodingRuntime
    goals: GoalRuntime
    peers: PeerRuntime
    artifacts: ArtifactAuthoringRuntime
    browser: BrowserFabricRuntime
    desktop: DesktopFabricRuntime
    extensions: ExtensionRuntime
    lifecycle: LifecycleRuntime
