"""Managed SearXNG sidecar for free local web search.

VARIANT-1 does not ship a SearXNG binary (it is a multi-service Python app). Instead
we manage a **named Docker/Podman container** (``searxng/searxng``) the same way
``LlamaServer`` owns ``llama-server.exe``:

* **autostart=true** (default) — start on backend launch when provider is searxng
* **autostart=false** — stay cold; Settings "Start" button runs it on demand
* **shutdown** — stop the container VARIANT-1 owns so it does not outlive the app

If Docker/Podman is missing, status reports that clearly and users can still
point ``base_url`` at any external instance.

Config lives under ``tools.json`` → ``web_search.searxng`` (see ToolsConfig).
"""

from __future__ import annotations

import asyncio
import os
import secrets
import shutil
import sys
from typing import Any
from urllib.parse import urlparse

import httpx

from process_tree import (
    attach_process_and_reap,
    dispose_process_tree,
    settle_process,
    tcp_port_is_free,
)

_NO_WINDOW = 0x08000000 if sys.platform.startswith("win") else 0

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8888
DEFAULT_IMAGE = "docker.io/searxng/searxng:latest"
DEFAULT_CONTAINER = "variant1-searxng"
CONTAINER_PORT = 8080


class SearxngError(RuntimeError):
    """Managed SearXNG is unavailable or failed to start."""


def find_container_runtime() -> str | None:
    """Return path to docker or podman, preferring docker."""
    for name in ("docker", "podman"):
        path = shutil.which(name)
        if path:
            return path
    return None


def parse_base_url(base_url: str, *, default_host: str = DEFAULT_HOST,
                   default_port: int = DEFAULT_PORT) -> tuple[str, int]:
    raw = (base_url or "").strip() or f"http://{default_host}:{default_port}"
    parsed = urlparse(raw if "://" in raw else f"http://{raw}")
    host = parsed.hostname or default_host
    port = int(parsed.port or default_port)
    return host, port


def settings_yml_body(secret_key: str) -> str:
    """Minimal overlay: use upstream defaults + enable JSON API for web_search."""
    key = (secret_key or secrets.token_hex(16)).replace('"', "")
    return (
        "# Generated by VARIANT-1 for the managed SearXNG container.\n"
        "# use_default_settings keeps engines/UI from upstream; we only\n"
        "# enable JSON format (required by web_search) and set a secret.\n"
        "use_default_settings: true\n"
        "\n"
        "server:\n"
        f'  secret_key: "{key}"\n'
        "  limiter: false\n"
        "  image_proxy: false\n"
        "\n"
        "search:\n"
        "  formats:\n"
        "    - html\n"
        "    - json\n"
    )


def ensure_settings_dir(
    config_dir: str,
    *,
    secret_key: str | None = None,
    bundled_settings: str | None = None,
) -> str:
    """Write settings.yml if missing. Returns the directory to mount at /etc/searxng."""
    dest = os.path.join(config_dir, "searxng")
    os.makedirs(dest, exist_ok=True)
    path = os.path.join(dest, "settings.yml")
    if not os.path.isfile(path):
        body = ""
        if bundled_settings and os.path.isfile(bundled_settings):
            try:
                with open(bundled_settings, "r", encoding="utf-8") as src:
                    body = src.read()
            except OSError:
                body = ""
        if not body.strip():
            body = settings_yml_body(secret_key or secrets.token_hex(16))
        elif "variant1-dev-replace-on-first-run" in body:
            body = body.replace(
                "variant1-dev-replace-on-first-run",
                secret_key or secrets.token_hex(16),
            )
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(body)
    return dest


class SearxngServer:
    """Owns the VARIANT-1-managed SearXNG container lifecycle."""

    def __init__(self, cfg: dict | None = None, *, data_dir: str = "", app_root: str = ""):
        c = dict(cfg or {}) if isinstance(cfg, dict) else {}
        self.data_dir = data_dir or ""
        self.app_root = app_root or ""
        self.autostart = bool(c.get("autostart", False))
        # managed=true: VARIANT-1 starts/stops the container. managed=false: attach only.
        self.managed = bool(c.get("managed", True))
        self.docker_image = str(c.get("docker_image") or DEFAULT_IMAGE).strip() or DEFAULT_IMAGE
        self.container_name = str(
            c.get("container_name") or DEFAULT_CONTAINER
        ).strip() or DEFAULT_CONTAINER
        host, port = parse_base_url(
            str(c.get("base_url") or ""),
            default_host=str(c.get("host") or DEFAULT_HOST),
            default_port=int(c.get("port") or DEFAULT_PORT),
        )
        if c.get("host"):
            host = str(c.get("host") or host)
        if c.get("port"):
            try:
                port = int(c.get("port") or port)
            except (TypeError, ValueError):
                pass
        self.host = host
        self.port = port
        self.ready = False
        self.last_error = ""
        self._owned = False  # True if this process started/attached as owner
        self._container_running = False
        self._runtime: str | None = None
        self._start_lock: asyncio.Lock | None = None
        self._autostart_task: asyncio.Task | None = None

    @property
    def base_url(self) -> str:
        return f"http://{self.host}:{self.port}"

    def _uses_local_managed_endpoint(self) -> bool:
        return self.host.strip().lower() in {
            "127.0.0.1", "localhost", "::1", "0.0.0.0",
        }

    def configure(self, cfg: dict | None) -> bool:
        """Refresh settings from tools.json without dropping live process state."""
        c = dict(cfg or {}) if isinstance(cfg, dict) else {}
        if "autostart" in c:
            self.autostart = bool(c.get("autostart"))
        if "managed" in c:
            self.managed = bool(c.get("managed"))
        if c.get("docker_image"):
            self.docker_image = str(c.get("docker_image")).strip() or self.docker_image
        if c.get("container_name"):
            self.container_name = str(c.get("container_name")).strip() or self.container_name
        host, port = parse_base_url(
            str(c.get("base_url") or self.base_url),
            default_host=self.host,
            default_port=self.port,
        )
        if c.get("host"):
            host = str(c.get("host") or host)
        if c.get("port") is not None:
            try:
                port = int(c.get("port") or port)
            except (TypeError, ValueError):
                pass
        address_changed = (host, port) != (self.host, self.port)
        # A live owned container must be stopped by ``reconfigure`` before its
        # published address changes. Cold/external managers can rebind now.
        if not self.ready and not self._container_running:
            self.host = host
            self.port = port
        return address_changed

    async def reconfigure(self, cfg: dict | None) -> None:
        c = dict(cfg or {}) if isinstance(cfg, dict) else {}
        host, port = parse_base_url(
            str(c.get("base_url") or self.base_url),
            default_host=self.host,
            default_port=self.port,
        )
        if c.get("host"):
            host = str(c.get("host") or host)
        if c.get("port") is not None:
            try:
                port = int(c.get("port") or port)
            except (TypeError, ValueError):
                pass
        address_changed = (host, port) != (self.host, self.port)
        if address_changed and (self._owned or self._container_running):
            await self.stop(force=True)
        self.ready = False if address_changed else self.ready
        if address_changed:
            self._container_running = False
        self.configure(c)
        if address_changed:
            self.host, self.port = host, port

    def runtime_path(self) -> str | None:
        if self._runtime and os.path.isfile(self._runtime):
            return self._runtime
        self._runtime = find_container_runtime()
        return self._runtime

    def docker_available(self) -> bool:
        return bool(self.runtime_path())

    def public_status(self) -> dict[str, Any]:
        return {
            "autostart": self.autostart,
            "managed": self.managed,
            "ready": self.ready,
            "owned": self._owned,
            "running": self._container_running,
            "base_url": self.base_url,
            "host": self.host,
            "port": self.port,
            "container_name": self.container_name,
            "docker_image": self.docker_image,
            "docker_available": self.docker_available(),
            "runtime": os.path.basename(self.runtime_path() or "") or "",
            "error": self.last_error or "",
        }

    async def _run_cli(self, args: list[str], *, timeout: float = 120.0) -> tuple[int, str, str]:
        runtime = self.runtime_path()
        if not runtime:
            raise SearxngError(
                "Docker/Podman not found on PATH. Install Docker Desktop to run "
                "the bundled SearXNG, or set web_search.searxng.base_url to an "
                "external instance."
            )
        try:
            proc = await asyncio.create_subprocess_exec(
                runtime,
                *args,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                creationflags=_NO_WINDOW,
                start_new_session=os.name != "nt",
            )
        except FileNotFoundError as e:
            raise SearxngError(f"could not launch container runtime: {e}") from e
        owner = await attach_process_and_reap(None, proc)
        try:
            out_b, err_b = await asyncio.wait_for(proc.communicate(), timeout=timeout)
        except asyncio.TimeoutError as e:
            if owner is not None:
                dispose_process_tree(owner, terminate=True)
                owner = None
            else:
                try:
                    proc.kill()
                except Exception:
                    pass
            await settle_process(proc, timeout_s=5.0)
            raise SearxngError(f"container command timed out: docker {' '.join(args[:3])}") from e
        finally:
            if owner is not None:
                dispose_process_tree(owner, terminate=proc.returncode is None)
                if proc.returncode is None:
                    await settle_process(proc, timeout_s=5.0)
        out = (out_b or b"").decode("utf-8", errors="replace").strip()
        err = (err_b or b"").decode("utf-8", errors="replace").strip()
        return int(proc.returncode or 0), out, err

    async def _container_state(self) -> str:
        """Return 'running' | 'exited' | 'missing' | 'unknown'."""
        code, out, _ = await self._run_cli(
            ["inspect", "-f", "{{.State.Running}}", self.container_name],
            timeout=15.0,
        )
        if code != 0:
            return "missing"
        text = (out or "").strip().lower()
        if text == "true":
            return "running"
        if text == "false":
            return "exited"
        return "unknown"

    async def _wait_healthy(self, timeout_s: float) -> bool:
        deadline = asyncio.get_event_loop().time() + timeout_s
        url = f"{self.base_url}/search"
        async with httpx.AsyncClient(timeout=2.0, trust_env=False) as client:
            while asyncio.get_event_loop().time() < deadline:
                try:
                    r = await client.get(
                        url,
                        params={"q": "variant1-health", "format": "json"},
                        headers={"Accept": "application/json"},
                    )
                    payload = r.json() if r.status_code == 200 else None
                    if (
                        r.status_code == 200
                        and isinstance(payload, dict)
                        and isinstance(payload.get("results"), list)
                    ):
                        return True
                except Exception:
                    pass
                await asyncio.sleep(0.5)
        return False

    async def probe(self) -> bool:
        """Non-destructive health probe of base_url."""
        try:
            ok = await self._wait_healthy(2.5)
            self.ready = ok
            if (
                self.managed
                and self._uses_local_managed_endpoint()
                and self.docker_available()
            ):
                state = await self._container_state()
                self._container_running = state == "running"
                if self._container_running:
                    self._owned = True
            if ok:
                self.last_error = ""
            return ok
        except Exception as e:
            self.ready = False
            self.last_error = str(e)
            return False

    def _settings_mount_dir(self) -> str:
        config_dir = os.path.join(self.data_dir, "config") if self.data_dir else ""
        if not config_dir:
            config_dir = os.path.join(self.app_root or ".", "config")
        bundled = ""
        if self.app_root:
            bundled = os.path.join(self.app_root, "config", "searxng", "settings.yml")
        return ensure_settings_dir(config_dir, bundled_settings=bundled or None)

    async def start(self, *, ready_timeout_s: float = 90.0, force: bool = False) -> None:
        """Start or attach to SearXNG. force=True ignores autostart=false (manual Start)."""
        if self._start_lock is None:
            self._start_lock = asyncio.Lock()
        async with self._start_lock:
            await self._start_unlocked(ready_timeout_s=ready_timeout_s, force=force)

    async def _start_unlocked(self, *, ready_timeout_s: float, force: bool) -> None:
        self.last_error = ""
        # Already healthy (external or previously started) — reuse.
        if await self._wait_healthy(2.0):
            self.ready = True
            if (
                self.managed
                and self._uses_local_managed_endpoint()
                and self.docker_available()
            ):
                state = await self._container_state()
                self._container_running = state == "running"
                self._owned = self._owned or self._container_running
            print(f"[searxng] ready at {self.base_url} (already listening)", flush=True)
            return

        if not self.managed:
            self.ready = False
            self.last_error = (
                f"no SearXNG reachable at {self.base_url} "
                "(managed=false; start your own instance or enable managed)"
            )
            raise SearxngError(self.last_error)

        if not force and not self.autostart:
            self.ready = False
            self.last_error = "autostart disabled; use Settings → Start SearXNG"
            raise SearxngError(self.last_error)

        if not self.docker_available():
            self.ready = False
            self.last_error = (
                "Docker/Podman not found. Install Docker Desktop for managed SearXNG, "
                f"or run an instance at {self.base_url}."
            )
            raise SearxngError(self.last_error)

        state = await self._container_state()
        self._container_running = state == "running"
        if state == "running":
            self._owned = True
            # Container up but our port probe failed — wrong port or still booting.
            if await self._wait_healthy(ready_timeout_s):
                self.ready = True
                self._owned = True
                print(f"[searxng] ready at {self.base_url} (existing container)", flush=True)
                return
            self.last_error = (
                f"container {self.container_name} is running but "
                f"{self.base_url} did not become healthy"
            )
            raise SearxngError(self.last_error)

        if state == "exited":
            print(f"[searxng] starting existing container {self.container_name}", flush=True)
            code, _out, err = await self._run_cli(["start", self.container_name], timeout=60.0)
            if code != 0:
                self.last_error = err or f"docker start failed (code {code})"
                raise SearxngError(self.last_error)
        else:
            # missing → create
            if not tcp_port_is_free(self.host, self.port):
                # Something else is on the port (not healthy for HTTP earlier).
                self.last_error = (
                    f"port {self.host}:{self.port} is in use but not serving SearXNG"
                )
                raise SearxngError(self.last_error)
            settings_dir = self._settings_mount_dir()
            # Docker Desktop on Windows wants host paths; normalize for volume flag.
            vol = os.path.abspath(settings_dir)
            args = [
                "run",
                "-d",
                "--name", self.container_name,
                "--label", "com.variant1.managed=searxng",
                "-p", f"127.0.0.1:{self.port}:{CONTAINER_PORT}",
                "-v", f"{vol}:/etc/searxng:rw",
                "-e", f"SEARXNG_BASE_URL={self.base_url}/",
                "--restart", "no",
                self.docker_image,
            ]
            print(f"[searxng] docker {' '.join(args)}", flush=True)
            try:
                code, _out, err = await self._run_cli(args, timeout=180.0)
            except SearxngError:
                state = await self._reconcile_ambiguous_start()
                if state != "running":
                    raise
                code, err = 0, ""
            if code != 0:
                self.last_error = err or f"docker run failed (code {code})"
                raise SearxngError(self.last_error)

        if not await self._wait_healthy(ready_timeout_s):
            self.ready = False
            self.last_error = f"SearXNG did not become healthy at {self.base_url}"
            # Best-effort stop so we do not leave a half-broken container racing.
            try:
                await self._run_cli(["stop", self.container_name], timeout=30.0)
            except Exception:
                pass
            raise SearxngError(self.last_error)

        self.ready = True
        self._owned = True
        self._container_running = True
        self.last_error = ""
        print(f"[searxng] ready at {self.base_url}", flush=True)

    async def _reconcile_ambiguous_start(self, *, timeout_s: float = 15.0) -> str:
        deadline = asyncio.get_event_loop().time() + max(1.0, float(timeout_s))
        last = "unknown"
        while asyncio.get_event_loop().time() < deadline:
            try:
                last = await self._container_state()
            except Exception:
                last = "unknown"
            if last == "running":
                self._container_running = True
                self._owned = True
                return last
            if last == "exited":
                self._container_running = False
                try:
                    await self._run_cli(["rm", "-f", self.container_name], timeout=30.0)
                except Exception:
                    pass
                return last
            await asyncio.sleep(0.5)
        return last

    async def stop(self, *, force: bool = False) -> None:
        """Stop the managed container. force=True stops even if not owned by us."""
        self.ready = False
        retry_task = self._autostart_task
        if retry_task is not None and retry_task is not asyncio.current_task():
            self._autostart_task = None
            retry_task.cancel()
            await asyncio.gather(retry_task, return_exceptions=True)
        if not self.managed and not force:
            return
        if not self._owned and not force:
            # We never started it this session — leave external instances alone.
            return
        if not self.docker_available():
            return
        try:
            state = await self._container_state()
            self._container_running = state == "running"
            if state == "running":
                print(f"[searxng] stopping container {self.container_name}", flush=True)
                await self._run_cli(["stop", self.container_name], timeout=45.0)
            state = await self._container_state()
            self._container_running = state == "running"
        except Exception as e:
            print(f"[searxng] stop warning: {e}", flush=True)
            try:
                self._container_running = await self._container_state() == "running"
            except Exception:
                self._container_running = True
        if not self._container_running:
            self._owned = False

    async def _autostart_retry_loop(self) -> None:
        delay = 3.0
        try:
            while self.managed and self.autostart and not self.ready:
                await asyncio.sleep(delay)
                try:
                    await self.start(force=False)
                except Exception as exc:
                    self.last_error = str(exc)
                    delay = min(30.0, delay * 1.7)
                    continue
                return
        finally:
            if self._autostart_task is asyncio.current_task():
                self._autostart_task = None

    def _schedule_autostart_retry(self) -> None:
        if self._autostart_task is None or self._autostart_task.done():
            self._autostart_task = asyncio.create_task(
                self._autostart_retry_loop(), name="searxng-autostart-retry"
            )

    async def ensure_started_if_autostart(self) -> None:
        """Lifecycle hook: start when autostart+managed, never raise to kill boot."""
        if not self.managed or not self.autostart:
            # Still probe so Settings can show "already running" for external instances.
            await self.probe()
            return
        try:
            await self.start(force=False)
        except SearxngError as e:
            print(f"[searxng] autostart skipped: {e}", flush=True)
            self._schedule_autostart_retry()
        except Exception as e:
            self.last_error = str(e)
            print(f"[searxng] autostart failed: {e}", flush=True)
            self._schedule_autostart_retry()
