"""Pin the installed, validated dependency closure of requirements.txt."""
from __future__ import annotations

import argparse
from collections import deque
from importlib import metadata
import os
from pathlib import Path
import platform
import sys
import tempfile

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


def declared_requirements(path):
    result = []
    for number, line in enumerate(Path(path).read_text(encoding="utf-8-sig").splitlines(), 1):
        line = line.split(" #", 1)[0].strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("-"):
            raise ValueError(f"Unsupported requirements directive at {path}:{number}; refusing an incomplete lock")
        result.append(Requirement(line))
    return result


def resolve_installed(requirements, *, distribution=metadata.distribution):
    pending = deque(requirements)
    selected, expanded = {}, {}
    while pending:
        requirement = pending.popleft()
        if requirement.marker and not requirement.marker.evaluate():
            continue
        if requirement.url:
            raise ValueError(f"Direct URL requirement needs an explicit lock strategy: {requirement.name}")
        name = canonicalize_name(requirement.name)
        installed = distribution(name)
        if requirement.specifier and not requirement.specifier.contains(installed.version, prereleases=True):
            raise ValueError(f"Installed {name}=={installed.version} does not satisfy {requirement}")
        extras = selected.get(name, (installed.version, set()))[1] | set(requirement.extras)
        selected[name] = (installed.version, extras)
        if name in expanded and extras <= expanded[name]:
            continue
        expanded[name] = set(extras)
        for text in installed.requires or ():
            dependency = Requirement(text)
            if dependency.marker and not any(dependency.marker.evaluate({"extra": extra}) for extra in {"", *extras}):
                continue
            # The marker belongs to the requiring distribution's extras and has
            # now been evaluated; do not reinterpret it as the child's extras.
            dependency.marker = None
            pending.append(dependency)
    return selected


def write_lock(path, selected):
    lines = ["# Complete installed dependency closure of backend/requirements.txt.",
             "# Generated by scripts/generate_backend_lock.py; do not trim by hand.",
             f"# Target environment: Python {platform.python_version()} / {sys.platform}.",
             "# Validate in a fresh matching environment before release.", ""]
    for name, (version, extras) in sorted(selected.items()):
        suffix = "[" + ",".join(sorted(extras)) + "]" if extras else ""
        lines.append(f"{name}{suffix}=={version}")
    target = Path(path).resolve()
    fd, temporary = tempfile.mkstemp(prefix=target.name + ".", suffix=".tmp", dir=target.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write("\n".join(lines) + "\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, target)
    finally:
        if os.path.exists(temporary): os.unlink(temporary)


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--requirements", type=Path, default=root / "backend/requirements.txt")
    parser.add_argument("--output", type=Path, default=root / "backend/requirements.lock")
    args = parser.parse_args()
    selected = resolve_installed(declared_requirements(args.requirements))
    write_lock(args.output, selected)
    print(f"Wrote {len(selected)} validated distribution pins to {args.output}")
