import assert from "node:assert/strict";
import {act} from "react";
import {createRoot} from "react-dom/client";
import {PeerControl} from "../frontend/main-deck/src/peers/PeerControl";
import {GrokControl} from "../frontend/main-deck/src/peers/GrokControl";
import {GrokDeliveryControl} from "../frontend/main-deck/src/peers/GrokDeliveryControl";
import {parseGrokBinding} from "../frontend/main-deck/src/peers/grokBindings";
import {PeerTranscriptMessage} from "../frontend/main-deck/src/peers/PeerTranscriptMessage";
import {chatMessagesMatch,parseMessage} from "../frontend/main-deck/src/chat/messages";
import {disposeTerminalRuntime,getTerminalSnapshot,ingestTerminal} from "../frontend/main-deck/src/context/terminalStore";
import {getWorkbenchState} from "../frontend/main-deck/src/workbench/workbenchStore";
import {disposePeers,ingestPeers,setPeerConnection,setPeerContext} from "../frontend/main-deck/src/peers/peerStore";

const wait=()=>new Promise(resolve=>setTimeout(resolve,180));
const button=(text:string)=>[...document.querySelectorAll<HTMLButtonElement>("button")].find(node=>node.textContent===text)!;
async function click(node:HTMLElement){assert.ok(node);await act(async()=>{node.click();});}
async function input(node:HTMLTextAreaElement,value:string) {
  await act(async()=>{Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,"value")!.set!.call(node,value);node.dispatchEvent(new Event("input",{bubbles:true}));});
}
export async function run() {
  const sent:Record<string,unknown>[]=[];
  const host=document.createElement("div");document.body.appendChild(host);const root=createRoot(host);
  setPeerContext({notify(){},send:command=>{sent.push(command);return true;}});setPeerConnection("connected");
  const last=(type:string)=>[...sent].reverse().find(command=>command.type===type)!;
  const ack=async(type:string,result:Record<string,unknown>)=>{const command=last(type);assert.ok(command);await act(async()=>ingestPeers({type:"peers:result",chat_id:command.chat_id,request_id:command.request_id,operation:type.slice(6),ok:true,result}));};
  const message={message_id:"message-1",exchange_id:"exchange-1",sender_peer_id:"canonical-a",target_peer_id:"canonical-b",content:"Check the parser",message_kind:"request",state:"queued",sequence:1,revision:1};
  try {
    await act(async()=>root.render(<PeerControl chatId="chat-a"/>));
    assert.equal(sent.length,0,"closed composer peer control makes no requests");
    await click(document.querySelector('[aria-label="Peers"]')!);await act(wait);
    await ack("peers:list",{items:[{peer_id:"canonical-a",kind:"variant_chat",chat_id:"chat-a",display_name:"Alpha",status:"idle"},{peer_id:"canonical-b",kind:"variant_chat",chat_id:"chat-b",display_name:"Beta",status:"busy"}]});
    await ack("peers:inbox",{peer_id:"canonical-a",messages:[],cursor:0,revision:0});
    assert.equal(document.querySelectorAll(".peer-directory button").length,1,"own chat is not a second independent peer");
    await click(document.querySelector(".peer-directory button")!);
    await input(document.querySelector('[aria-label="Peer message"]')!,"Check the parser");
    await click(button("Send to peer"));
    assert.equal(last("peers:send").message_kind,"request");assert.equal(last("peers:send").peer_id,"canonical-b");assert.equal(last("peers:send").chat_id,"chat-a");
    const count=sent.filter(row=>row.type==="peers:send").length;await click(button("Sending…"));
    assert.equal(sent.filter(row=>row.type==="peers:send").length,count,"disabled pending submit cannot duplicate a send");
    await ack("peers:send",{...message,request_id:last("peers:send").request_id});
    assert.equal((document.querySelector('[aria-label="Peer message"]') as HTMLTextAreaElement).value,"");
    await click(button("Sent"));assert.match(document.querySelector(".peer-message")!.textContent!,/Queued/);
    assert.doesNotMatch(document.querySelector(".peer-message__state")!.textContent!,/Observed|Reply/);
    await act(async()=>root.render(<PeerControl chatId="chat-b"/>));await act(wait);
    assert.equal(document.querySelector('[aria-label="Peer message"]'),null,"switching chats cannot carry a recipient selection into another owner");
    await ack("peers:list",{items:[{peer_id:"canonical-a",kind:"variant_chat",chat_id:"chat-a",display_name:"Alpha",status:"idle"},{peer_id:"canonical-b",kind:"variant_chat",chat_id:"chat-b",display_name:"Beta",status:"busy"}]});
    await ack("peers:inbox",{peer_id:"canonical-b",messages:[message],cursor:1,revision:1});
    await click(button("Inbox"));await click(button("Reply"));
    await input(document.querySelector('[aria-label="Peer message"]')!,"Found a boundary error");await click(button("Send to peer"));
    assert.equal(last("peers:reply").message_kind,"result","reply defaults to result");assert.equal(last("peers:reply").chat_id,"chat-b");assert.equal(last("peers:reply").message_id,"message-1");
    assert.match(document.querySelector(".peer-compose")!.textContent!,/does not start new work/);
    await click(document.querySelector('[aria-label="Close peers"]')!);
    const before=sent.length;await act(async()=>ingestPeers({type:"peer:changed",chat_id:"chat-b",peer_id:"canonical-b",message_id:"message-1",revision:2}));await act(wait);
    assert.equal(sent.length,before,"closed overlay never polls or refreshes on push");
    await act(async()=>root.render(<GrokControl chatId="chat-a" terminalId="manual-terminal"/>));
    await click(button("Grok"));await act(wait);
    await ack("peers:grok:status",{available:true,installed:true,adapter:"grok-peer-bridge",items:[{binding_id:"binding-a",viewer_chat_id:"chat-a",owner_chat_id:"chat-other",delivery_mode:"inbox",capabilities:{live_ingress:false},session_id:"grok-session",terminal_id:"connected-terminal",peer_id:"grok-peer",status:"ready",pending_permissions:[{binding_id:"binding-a",session_id:"grok-session",permission_id:"permission-a",tool_call:{title:"Read file"},options:[{optionId:"once",name:"Allow once",kind:"allow_once"},{optionId:"deny",name:"Reject",kind:"reject_once"}]}]},{binding_id:"foreign",viewer_chat_id:"chat-b",owner_chat_id:"chat-a",status:"ready"}]});
    assert.equal(document.querySelectorAll(".grok-peer-binding").length,1,"viewer correlation governs discovery, not original launch ownership");
    assert.match(document.querySelector(".grok-delivery-mode")!.textContent!,/Inbox only/);
    assert.equal(button("Show terminal").disabled,true,"a global connection cannot select a terminal absent from this chat");
    await ack("peers:grok:sessions",{viewer_chat_id:"chat-a",items:[{session_id:"saved-session-a",title:"Existing study",cwd:"C:/Studies/Original"}],cursor:null});
    const directory=document.querySelector('[aria-label="Grok directory"]') as HTMLInputElement;
    assert.equal(directory.readOnly,false,"new-session directory remains editable");
    await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")!.set!.call(directory,"D:/New workspace");directory.dispatchEvent(new Event("input",{bubbles:true}));});
    const chooseSession=async(value:string)=>act(async()=>{const select=document.querySelector('[aria-label="Grok session"]') as HTMLSelectElement;select.value=value;select.dispatchEvent(new Event("change",{bubbles:true}));});
    await chooseSession("saved-session-a");
    assert.equal(directory.value,"C:/Studies/Original","saved sessions display their native directory");
    assert.equal(directory.readOnly,true,"saved sessions cannot be relocated through the launch form");
    await click(button("Refresh"));
    await ack("peers:grok:sessions",{viewer_chat_id:"chat-a",items:[{session_id:"saved-session-a",title:"Existing study",cwd:"C:/Studies/Original"}],cursor:null});
    await chooseSession("");
    assert.equal(directory.readOnly,false);assert.equal(directory.value,"D:/New workspace","saved-session browsing preserves the new-session directory draft");
    await chooseSession("saved-session-a");
    await click(button("Open saved session in terminal"));
    assert.equal(last("peers:grok:launch").session_id,"saved-session-a");assert.equal("cwd" in last("peers:grok:launch"),false,"resume delegates native directory resolution to the backend");assert.equal(last("peers:grok:launch").chat_id,"chat-a");
    // Complete the explicit refresh so the following binding invalidation can issue its own read.
    await ack("peers:grok:status",{available:true,installed:true,adapter:"grok-peer-bridge",items:[{binding_id:"binding-a",viewer_chat_id:"chat-a",owner_chat_id:"chat-other",session_id:"grok-session",terminal_id:"",peer_id:"grok-peer",status:"connected",delivery_mode:"inbox",capabilities:{live_ingress:false},pending_permissions:[{binding_id:"binding-a",session_id:"grok-session",permission_id:"permission-a",tool_call:{title:"Read file"},options:[{optionId:"once",name:"Allow once",kind:"allow_once"},{optionId:"deny",name:"Reject",kind:"reject_once"}]}]}]});
    const beforeEvent=sent.filter(row=>row.type==="peers:grok:status").length;
    await act(async()=>ingestPeers({type:"peers:grok:changed",chat_id:"chat-b",binding_id:"foreign",revision:1}));await act(wait);
    assert.equal(sent.filter(row=>row.type==="peers:grok:status").length,beforeEvent,"foreign binding updates do not refresh this dialog");
    await act(async()=>ingestPeers({type:"peers:grok:changed",chat_id:"chat-a",binding_id:"binding-a",revision:1}));await act(wait);
    assert.equal(sent.filter(row=>row.type==="peers:grok:status").length,beforeEvent+1,"open owner dialog refreshes on binding and permission changes");
    assert.equal(button("Grok").textContent,"Grok","ordinary terminal is not inferred to own an ACP binding");
    await click(button("Allow once"));
    assert.equal(last("peers:grok:permission").binding_id,"binding-a");assert.equal(last("peers:grok:permission").permission_id,"permission-a");assert.equal(last("peers:grok:permission").option_id,"once");
    await act(async()=>setPeerConnection("offline"));assert.equal(button("Reject").disabled,true,"uncertain permission blocks a contradictory answer");
    const attributed=parseMessage({role:"user",text:"[Peer message] Message ID: hidden-envelope",peer_display:{display_name:"Grok Build",content:"Check the parser"},origin:{kind:"peer",peer_id:"canonical-a",message_id:"message-1"}})!;
    const human=parseMessage({role:"user",text:"Check the parser"})!;
    assert.equal(chatMessagesMatch(human,attributed),false,"peer provenance cannot match away an optimistic human message with identical text");
    assert.equal(parseMessage({role:"user",text:"[Peer canonical-a] says hello"})?.origin,undefined,"peer attribution is never inferred from message text");
    await act(async()=>root.render(<PeerTranscriptMessage message={{...attributed,origin:attributed.origin!}}/>));
    assert.match(document.querySelector('[aria-label="Message from Grok Build"]')!.textContent!,/Sent by Grok Build/);
    assert.equal(document.querySelector(".peer-chat")!.textContent!.includes("hidden-envelope"),false);
    assert.equal(document.querySelector(".peer-chat details"),null,"chat peers do not expose receipt identities");
    const longMessage={...attributed,origin:attributed.origin!,peerDisplay:{display_name:"Grok Build",content:"A useful message about the work. ".repeat(30)}};
    await act(async()=>root.render(<PeerTranscriptMessage message={longMessage}/>));
    assert.equal(button("Show more").getAttribute("aria-expanded"),"false");await click(button("Show more"));
    assert.equal(document.querySelector(".peer-chat p")!.classList.contains("is-collapsed"),false,"long peer messages expand without exposing transport metadata");
    assert.equal(document.querySelector('[aria-label="You"]'),null);
    await act(async()=>{setPeerConnection("connected");root.render(<GrokControl chatId="chat-local"/>);});
    await click(button("Grok"));await act(wait);
    await ack("peers:grok:status",{available:true,installed:true,adapter:"grok-peer-bridge",items:[{viewer_chat_id:"chat-local",owner_chat_id:"other-origin",binding_id:"local-binding",session_id:"native-session",terminal_chat_id:"chat-local",terminal_id:"local-terminal",status:"connected",delivery_mode:"agent_context_prompt",capabilities:{live_ingress:true}}]});
    await act(async()=>ingestTerminal({type:"execution:snapshot",chat_id:"chat-local",terminals:[{terminal_id:"local-terminal",state:"running",cwd:"C:/Example"}],processes:[]}));
    assert.equal(button("Show terminal").disabled,false);
    await click(button("Show terminal"));
    assert.equal(getTerminalSnapshot("chat-local").activeId,"local-terminal");
    assert.equal(getWorkbenchState().hidden["owned:terminal:chat-local"],false,"Show terminal reveals the chat-owned pane instead of only selecting a hidden terminal");
    await act(async()=>root.render(<GrokControl chatId="chat-a" terminalId=""/>));
    assert.ok(button("Grok"),"an inbox-only connection's empty terminal ID cannot match an empty terminal selection");
    await act(async()=>root.render(<GrokControl chatId="chat-profile"/>));await click(button("Grok"));await act(wait);
    const setupCount=sent.filter(row=>row.type==="peers:grok:setup").length;
    await ack("peers:grok:status",{available:true,installed:true,adapter:"grok-peer-bridge",profile_id:"current-profile",installation_profile_id:"other-profile",items:[]});
    await ack("peers:grok:sessions",{viewer_chat_id:"chat-profile",items:[],cursor:null});
    assert.equal(button("Launch Grok in terminal").disabled,true,"a different adapter profile blocks ordinary launch");
    assert.equal(sent.filter(row=>row.type==="peers:grok:setup").length,setupCount,"discovering a profile mismatch never switches automatically");
    assert.match(document.querySelector(".grok-peer-dialog")!.textContent!,/Currently running connections keep their existing profile/);
    await click(button("Switch adapter to this profile"));
    assert.equal(last("peers:grok:setup").replace_profile_id,"other-profile","explicit profile switch carries the exact observed old profile");
    const switchRequest=last("peers:grok:setup");
    await act(async()=>ingestPeers({type:"peers:result",chat_id:"chat-profile",request_id:switchRequest.request_id,operation:"grok:setup",ok:false,error:{code:"profile_changed",message:"Adapter profile changed. Refresh before switching.",commit_state:"not_committed"}}));
    assert.match(document.querySelector(".grok-peer-dialog")!.textContent!,/Adapter profile changed/);
    assert.equal(sent.filter(row=>row.type==="peers:grok:setup").length,setupCount+1,"stale compare-and-switch is shown, never retried automatically");
    const binding=parseGrokBinding({binding_id:"stock-binding",viewer_chat_id:"chat-stock",peer_id:"grok:stock",delivery_mode:"inbox",preferred_delivery_mode:"agent_context_prompt",automatic_wake_available:false,native_agent_origin:false},"chat-stock")!;
    await act(async()=>root.render(<GrokDeliveryControl chatId="chat-stock" binding={binding}/>));
    const automatic=document.querySelector<HTMLInputElement>('input[value="agent_context_prompt"]')!;
    assert.equal(automatic.checked,true,"unavailable wake does not discard the saved preference");assert.equal(automatic.disabled,true);
    assert.match(document.body.textContent!,/unavailable on this connection/);
    await click(document.querySelector('input[value="inbox"]')!);
    assert.equal(last("peers:grok:delivery").expected_delivery_mode,"agent_context_prompt","compare uses saved preference despite effective inbox fallback");
    assert.equal(last("peers:grok:delivery").delivery_mode,"inbox");assert.equal(last("peers:grok:delivery").peer_id,"grok:stock");
    assert.equal(sent.some(row=>["cancel","chat:stop","terminal:close"].includes(String(row.type))),false,"delivery choice never cancels admitted work");
    await ack("peers:grok:delivery",{viewer_chat_id:"chat-stock",peer_id:"grok:stock",delivery_mode:"inbox",preferred_delivery_mode:"inbox",automatic_wake_available:false,native_agent_origin:false});
    await act(async()=>root.render(<GrokDeliveryControl chatId="chat-stock" binding={{...binding,preferred_delivery_mode:"inbox",automatic_wake_available:true}}/>));
    assert.equal(document.querySelector<HTMLInputElement>('input[value="agent_context_prompt"]')!.disabled,false);
    await click(document.querySelector('input[value="agent_context_prompt"]')!);
    assert.equal(last("peers:grok:delivery").expected_delivery_mode,"inbox");assert.equal(last("peers:grok:delivery").delivery_mode,"agent_context_prompt");
    assert.match(document.body.textContent!,/user-input notification/);
    console.log("Peer UI: chat ownership, explicit send/reply, receipt semantics, closed-view silence, canonical Grok bindings and explicit permission passed");
  } finally {await act(async()=>{root.unmount();disposePeers();disposeTerminalRuntime();});host.remove();}
}
