import assert from "node:assert/strict";
import {act} from "react";
import {createRoot} from "react-dom/client";
import {ChatComposer} from "../frontend/main-deck/src/chat/ChatComposer";
import {__resetChatStoreForTests} from "../frontend/main-deck/src/chatStore";
import {activateChatState,getCachedChatState,getChatState,initialChatState,setChatContext,setChatState} from "../frontend/main-deck/src/chat/stateCore";
import {setChatDraft,submitUserInput} from "../frontend/main-deck/src/chat/composer";
import {ingestChat} from "../frontend/main-deck/src/chat/ingest";
import {applySession} from "../frontend/main-deck/src/chat/session";
import {setChatConnection} from "../frontend/main-deck/src/chat/connection";
import {mutateInputQueue,queueAdmissionPending} from "../frontend/main-deck/src/chat/inputQueue";
import {parseChatWsMessage} from "../frontend/main-deck/src/protocol";
import {parseInputQueueSnapshot,type InputQueueItem} from "../frontend/main-deck/src/protocol/chatQueue";
import {__resetSessionStoreForTests,noteDisplayedSession,setSessionConnection,setSessionContext} from "../frontend/main-deck/src/state/sessionStore";
import {__resetSessionContextStoreForTests} from "../frontend/main-deck/src/sessionContextStore";
import {__resetTurnStoreForTests} from "../frontend/main-deck/src/state/turnStore";
import {resetWireStatus} from "../frontend/main-deck/src/connectionUi";

const pause=()=>new Promise(resolve=>setTimeout(resolve,0));
const item=(id:string,state:InputQueueItem["state"]="parked",chat="A"):InputQueueItem=>({ticket_id:id,chat_id:chat,text:`Prompt ${id}`,delivery:"follow_up",state,client_id:"original-client",source:"chat",created_at:id,updated_at:id});
const snapshot=(revision:number,items:readonly InputQueueItem[],session="A",request_id?:string)=>({type:"chat:queue_snapshot",schema:"variant1.input-queue.v1",session_id:session,revision,items,request_id});

export async function run() {
  __resetChatStoreForTests();__resetSessionStoreForTests();__resetTurnStoreForTests();__resetSessionContextStoreForTests();resetWireStatus("chat");
  const commands:Array<Record<string,unknown>>=[];let online=true;
  const context={send:(command:Record<string,unknown>)=>{commands.push(command);return online;},isOpen:()=>online,notify(){}};
  setChatContext(context);setSessionContext(context);setSessionConnection("connected");
  setChatState({...initialChatState(),sessionId:"A",connected:true});noteDisplayedSession("A");
  const host=document.createElement("div");document.body.appendChild(host);const root=createRoot(host);
  const ingest=async(row:Record<string,unknown>)=>act(async()=>ingestChat(parseChatWsMessage(row)));
  const last=(type:string)=>commands.filter(command=>command.type===type).at(-1)!;
  const buttons=(id:string,label:string)=>Array.from(host.querySelectorAll<HTMLButtonElement>(`[data-queue-ticket="${id}"] button`)).find(button=>button.textContent===label)!;
  const queueIds=()=>getChatState().inputQueue.snapshot!.items.map(item=>item.ticket_id);
  const count=(id:string)=>getChatState().messages.filter(message=>message.role==="user"&&message.ticketId===id).length;
  try {
    await act(async()=>{root.render(<ChatComposer/>);await pause();});
    await act(async()=>setChatDraft("untouched draft"));
    await ingest(snapshot(5,[item("a"),item("b")]));
    assert.deepEqual(Array.from(host.querySelectorAll('[data-queue-ticket]')).map(row=>(row as HTMLElement).dataset.queueTicket),["a","b"]);
    assert.equal(getChatState().turnActive,false);assert.equal(host.querySelector('[aria-label="Resume task"]'),null);
    assert.equal(buttons("a","Continue").disabled,false);assert.equal(getChatState().draft,"untouched draft");
    await ingest(snapshot(4,[]));await ingest(snapshot(5,[]));assert.deepEqual(queueIds(),["a","b"]);
    assert.equal(parseInputQueueSnapshot(snapshot(6,[item("a"),item("a")])),null);
    await ingest(snapshot(6,[item("wrong","parked","B")]));assert.deepEqual(queueIds(),["a","b"]);
    await ingest({type:"chat:queue_settled",session_id:"A",ids:["a","b"],reason:"cancelled",queue_size:0});
    await ingest({type:"chat:queued",session_id:"A",id:"old",delivery:"steer",queue_size:20});
    await ingest({type:"chat:queue_progress",session_id:"A",id:"a",delivery:"follow_up",queue_size:0});
    assert.deepEqual(queueIds(),["a","b"]);assert.equal(getChatState().draft,"untouched draft");assert.equal(count("a"),0);
    assert.equal(commands.filter(command=>command.type==="chat:queue:get").length,1,"legacy refreshes coalesce and never mutate canonical tickets");
    await ingest(snapshot(5,[item("a"),item("b")],"A",String(last("chat:queue:get").request_id)));
    await act(async()=>submitUserInput({source:"voice",sessionId:"A",text:"What did you find?"}));
    assert.equal(last("chat").text,"What did you find?");assert.deepEqual(queueIds(),["a","b"]);
    assert.equal(buttons("a","Continue").disabled,true);
    await ingest({type:"start",session_id:"A",client_id:getChatState().clientId,admission_id:"ordinary",run_id:"ordinary"});
    await ingest({type:"done",session_id:"A",client_id:getChatState().clientId,admission_id:"ordinary",run_id:"ordinary",text:"Findings"});
    assert.deepEqual(queueIds(),["a","b"]);assert.equal(getChatState().draft,"untouched draft");

    await act(async()=>{buttons("a","Continue").click();buttons("a","Continue").click();});
    const first=last("chat:queue:continue"),request=String(first.request_id);
    assert.equal(commands.filter(command=>command.type==="chat:queue:continue").length,1);
    assert.equal(first.ticket_id,"a");assert.equal(first.expected_revision,5);assert.equal(first.session_id,"A");assert.ok(queueAdmissionPending());assert.equal(count("a"),0);
    assert.equal(submitUserInput({source:"voice",sessionId:"A",text:"admission race"}),false);
    await ingest({type:"chat:queue_result",operation:"continue",session_id:"A",request_id:request,accepted:true,queue:snapshot(6,[item("a","selected"),item("b")])});
    assert.equal(count("a"),0,"acceptance does not fabricate a started prompt");assert.equal(buttons("a","Remove").disabled,true);
    const route={session_id:"A",source:"queue_continue",client_id:request,request_id:request,ticket_id:"a",admission_id:"continued-a",run_id:"continued-a"};
    await ingest({type:"start",...route});assert.equal(count("a"),1);assert.equal(getChatState().turnActive,true);
    await ingest({type:"chat:queue_progress",session_id:"A",id:"a",delivery:"follow_up",queue_size:1,queue:snapshot(7,[item("b")])});
    assert.equal(count("a"),1);await ingest({type:"done",...route,text:"Answer a"});
    const committed=[{role:"user",text:"Prompt a",ticket_id:"a"},{role:"assistant",text:"Answer a"}];
    await ingest({type:"chat:appended",...route,messages:committed,user:committed[0],assistant:committed[1]});
    await ingest({type:"chat:appended",...route,messages:committed,user:committed[0],assistant:committed[1]});
    await ingest({type:"chat:queue_result",operation:"continue",session_id:"A",request_id:request,accepted:true,queue:snapshot(6,[item("a","selected"),item("b")])});
    assert.equal(count("a"),1);assert.equal(getChatState().turnActive,false);assert.deepEqual(queueIds(),["b"]);
    await ingest({type:"start",...route});assert.equal(getChatState().turnActive,false,"late duplicate start cannot revive the finished continuation");

    await act(async()=>buttons("b","Continue").click());const second=last("chat:queue:continue"),requestB=String(second.request_id);
    const routeB={session_id:"A",source:"queue_continue",client_id:requestB,request_id:requestB,ticket_id:"b",admission_id:"continued-b",run_id:"continued-b"};
    await ingest({type:"start",...routeB});assert.equal(count("b"),1);
    await ingest(snapshot(7,[item("b")]));assert.equal(count("b"),1,"pre-admission revision cannot erase a started prompt");
    await ingest(snapshot(8,[item("b","preparing")]));assert.equal(buttons("b","Remove").disabled,true);
    await ingest({type:"chat:queue_progress",session_id:"A",id:"b",delivery:"follow_up",queue:snapshot(9,[]),queue_size:0});
    await ingest({type:"done",...routeB,text:"Answer b"});
    await ingest({type:"chat:queue_result",operation:"continue",session_id:"A",request_id:requestB,accepted:true,queue:snapshot(8,[item("b","preparing")])});
    assert.equal(count("b"),1);assert.equal(getChatState().turnActive,false);assert.deepEqual(queueIds(),[]);assert.equal(getChatState().draft,"untouched draft");
    await act(async()=>submitUserInput({source:"voice",sessionId:"A",text:"new work after b"}));
    const committedB=[{role:"user",text:"Prompt b",ticket_id:"b"},{role:"assistant",text:"Answer b"}];
    await ingest({type:"chat:appended",...routeB,messages:committedB,user:committedB[0],assistant:committedB[1]});
    await ingest({type:"chat:appended",...routeB,messages:committedB,user:committedB[0],assistant:committedB[1]});
    assert.equal(count("b"),1,"late commit from the Continue request client deduplicates after a newer turn begins");
    await ingest({type:"start",session_id:"A",client_id:getChatState().clientId,admission_id:"new-work",run_id:"new-work"});
    await ingest({type:"done",session_id:"A",client_id:getChatState().clientId,admission_id:"new-work",run_id:"new-work",text:"New answer"});

    const eligible=[item("c","queued"),item("d","resume_queued"),item("e"),item("f","selected"),item("g","preparing")];
    await ingest(snapshot(10,eligible));
    assert.equal(mutateInputQueue("remove","f","A"),false);assert.equal(mutateInputQueue("continue","c","A"),false);
    await act(async()=>{buttons("c","Remove").click();buttons("c","Remove").click();});
    const removal=last("chat:queue:remove");assert.equal(commands.filter(command=>command.type==="chat:queue:remove").length,1);assert.equal(removal.expected_revision,10);
    await ingest({type:"chat:queue_result",operation:"remove",session_id:"A",request_id:removal.request_id,accepted:false,error:"stale queue revision",queue:snapshot(12,eligible)});
    assert.deepEqual(queueIds(),eligible.map(item=>item.ticket_id));assert.match(host.textContent!,/stale queue revision/);
    assert.equal(commands.filter(command=>command.type==="chat:queue:remove").length,1,"rejection never replays automatically");
    await act(async()=>buttons("e","Remove").click());const removeE=last("chat:queue:remove");
    await ingest({type:"chat:queue_result",operation:"remove",session_id:"A",request_id:removeE.request_id,accepted:true,queue:snapshot(13,eligible.filter(item=>item.ticket_id!=="e"))});
    assert.equal(queueIds().includes("e"),false);assert.equal(getChatState().draft,"untouched draft");
    await ingest(snapshot(11,eligible));assert.equal(queueIds().includes("e"),false);
    await act(async()=>applySession({id:"A",title:"A",messages:committed,runtime:{busy:false,input_queue:snapshot(13,eligible.filter(item=>item.ticket_id!=="e"))}}));
    assert.equal(queueIds().includes("d"),true,"idle session hydration retains queue");
    await act(async()=>buttons("d","Remove").click());const beforeReconnect=commands.filter(command=>command.type==="chat:queue:remove").length;
    online=false;await act(async()=>setChatConnection("offline"));assert.equal(getChatState().inputQueue.synced,false);
    online=true;await act(async()=>setChatConnection("connected"));
    const refresh=last("chat:queue:get");assert.ok(refresh.request_id);
    await ingest(snapshot(13,eligible.filter(item=>item.ticket_id!=="e")));
    await ingest(snapshot(13,eligible.filter(item=>item.ticket_id!=="e"),"A",String(refresh.request_id)));
    assert.equal(getChatState().inputQueue.action,undefined);assert.equal(commands.filter(command=>command.type==="chat:queue:remove").length,beforeReconnect);assert.equal(queueIds().includes("d"),true);
    await act(async()=>setChatState({...getChatState(),connected:true}));
    await act(async()=>buttons("d","Remove").click());
    const failed=last("chat:queue:remove"),saved=getChatState().inputQueue.snapshot;
    await ingest({type:"chat:queue_result",operation:"remove",session_id:"A",request_id:failed.request_id,accepted:false,error:"queue storage unavailable",queue:null});
    assert.equal(getChatState().inputQueue.snapshot,saved);assert.equal(getChatState().inputQueue.synced,false);assert.match(host.textContent!,/queue storage unavailable/);
    await act(async()=>host.querySelector<HTMLButtonElement>('[aria-label="Refresh queued messages"]')!.click());
    const failedRead=last("chat:queue:get");
    await ingest({type:"chat:queue_result",operation:"get",session_id:"A",request_id:failedRead.request_id,accepted:false,error:"queue read unavailable",queue:null});
    assert.equal(getChatState().inputQueue.refreshRequestId,undefined);assert.equal(getChatState().inputQueue.snapshot,saved);assert.match(host.textContent!,/queue read unavailable/);
    await act(async()=>{activateChatState("B");setChatState({...getChatState(),connected:true});noteDisplayedSession("B");});
    await ingest(snapshot(1,[item("b-only","parked","B")],"B"));
    await ingest(snapshot(14,[item("a-only")],"A"));assert.deepEqual(queueIds(),["b-only"]);assert.equal(getCachedChatState("A")!.inputQueue.snapshot!.items[0].ticket_id,"a-only");
    assert.equal(mutateInputQueue("continue","b-only","A"),false);
    await act(async()=>submitUserInput({source:"voice",sessionId:"B",text:"ordinary B work"}));
    const routeOrdinaryB={session_id:"B",client_id:getChatState().clientId,admission_id:"ordinary-b",run_id:"ordinary-b"};
    await ingest({type:"start",...routeOrdinaryB});
    await act(async()=>submitUserInput({source:"voice",sessionId:"B",text:"active steer"},"steer"));
    const activeTicket=String(last("chat").ticket_id),activeItem={...item(activeTicket,"queued","B"),text:"active steer",delivery:"steer" as const};
    await ingest({type:"chat:queued",session_id:"B",id:activeTicket,delivery:"steer",queue_size:1,queue:snapshot(2,[item("b-only","parked","B"),activeItem],"B")});
    assert.equal(count(activeTicket),0,"canonical undelivered prompt lives in queue only");assert.equal(getChatState().pendingActiveInputs.length,0);
    await ingest({type:"chat:queue_progress",session_id:"B",id:activeTicket,delivery:"steer",queue_size:0,queue:snapshot(3,[item("b-only","parked","B")],"B")});
    assert.equal(count(activeTicket),1,"confirmed delivery adds exactly one visible prompt");
    await ingest({type:"chat:queued",session_id:"B",id:activeTicket,delivery:"steer",queue_size:1,queue:snapshot(2,[activeItem],"B")});assert.equal(count(activeTicket),1);
    await act(async()=>submitUserInput({source:"voice",sessionId:"B",text:"park this after Stop"}));const parkedTicket=String(last("chat").ticket_id);
    await ingest({type:"done",...routeOrdinaryB,cancelled:true,text:"Stopped"});
    await ingest(snapshot(4,[item("b-only","parked","B"),{...item(parkedTicket,"parked","B"),text:"park this after Stop"}],"B"));
    assert.equal(getChatState().turnActive,false);assert.equal(count(parkedTicket),0);assert.equal(getChatState().draft,"");
    assert.equal(buttons(parkedTicket,"Continue").disabled,false,"parked work remains explicit and available after terminal cleanup");
    console.log("Input queue: ordered idle/rehydrated retention; normal Send isolation; revision/legacy ordering; exactly-once explicit Continue and committed prompt; eligible Remove, errors/null snapshots, reconnect and session isolation passed");
  } finally {
    await act(async()=>root.unmount());host.remove();resetWireStatus("chat");__resetChatStoreForTests();__resetSessionStoreForTests();__resetTurnStoreForTests();__resetSessionContextStoreForTests();
  }
}
