import assert from "node:assert/strict";
import {disposePeers,getPeerState,ingestPeers,inspectPeerRequest,peerDraftKey,peerRequestKey,requestPeer,retryPeerRequest,setPeerConnection,setPeerContext,setPeerDraft,submitPeerDraft} from "../frontend/main-deck/src/peers/peerStore";
import {grokDeliveryLabel,parseGrokSavedSession} from "../frontend/main-deck/src/peers/grokSessions";
import {parseGrokBinding} from "../frontend/main-deck/src/peers/grokBindings";

const message=(requestId:string,extra:Record<string,unknown>={})=>({message_id:"opaque-message",exchange_id:"exchange-1",sender_peer_id:"opaque-peer-a",target_peer_id:"opaque-peer-b",request_id:requestId,content:"Review the parser",in_reply_to:"",state:"queued",sequence:1,revision:1,...extra});

export function run() {
  const sent:Record<string,unknown>[]=[];
  setPeerContext({notify(){},send:command=>{sent.push(command);return true;}});
  setPeerConnection("connected");
  assert.equal(sent.length,0,"connection alone performs no peer operation");
  const list={operation:"list" as const},send={operation:"send" as const,peer_id:"opaque-peer-b",text:"Review the parser",delivery:"follow_up" as const};
  const read=requestPeer("chat-a",list)!;
  const write=requestPeer("chat-a",send)!;
  assert.equal(sent.at(-1)?.chat_id,"chat-a");
  assert.equal("sender_peer_id" in sent.at(-1)!,false,"the service derives sender identity");
  assert.equal(requestPeer("chat-a",send),null);
  ingestPeers({type:"peers:result",request_id:write,chat_id:"chat-c",operation:"send",ok:true,result:{status:"observed"}});
  ingestPeers({type:"peers:result",request_id:write,chat_id:"chat-a",operation:"reply",ok:true,result:{status:"observed"}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-a",send)].phase,"pending");
  setPeerConnection("offline");
  assert.equal(getPeerState().requests[peerRequestKey("chat-a",send)].phase,"unconfirmed");
  assert.equal(getPeerState().requests[peerRequestKey("chat-a",send)].submittedText,send.text);
  setPeerConnection("connected");
  assert.equal(sent.length,2,"reconnect must not replay a send");
  assert.equal(requestPeer("chat-a",send),null,"ambiguous sends remain guarded");
  const nextRead=requestPeer("chat-a",list)!;
  ingestPeers({type:"peers:result",request_id:read,chat_id:"chat-a",operation:"list",ok:true,result:{stale:true}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-a",list)].phase,"pending");
  ingestPeers({type:"peers:result",request_id:nextRead,chat_id:"chat-a",operation:"list",ok:true,result:{peers:[]}});
  ingestPeers({type:"peers:result",request_id:write,chat_id:"chat-a",operation:"send",ok:true,result:message(write)});
  const saved=getPeerState().requests[peerRequestKey("chat-a",send)];
  assert.equal(saved.phase,"accepted");assert.equal(saved.result?.state,"queued","envelope success cannot upgrade delivery evidence");
  const reply={operation:"reply" as const,message_id:"opaque-message",text:"Found the cause"};
  const replyId=requestPeer("chat-b",reply)!;
  ingestPeers({type:"peers:result",request_id:replyId,chat_id:"chat-b",operation:"reply",ok:false,error:{code:"unavailable",message:"Recipient unavailable"}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-b",reply)].submittedText,reply.text);
  assert.equal(getPeerState().requests[peerRequestKey("chat-b",reply)].error?.message,"Recipient unavailable");
  assert.equal(getPeerState().requests[peerRequestKey("chat-b",reply)].phase,"unconfirmed","RPC failure alone cannot exclude persistence");
  assert.equal(inspectPeerRequest("chat-c",replyId),null);
  const lookup=inspectPeerRequest("chat-b",replyId)!;
  assert.equal(sent.at(-1)?.lookup_request_id,replyId);
  assert.equal(sent.at(-1)?.chat_id,"chat-b");
  ingestPeers({type:"peers:result",request_id:lookup,chat_id:"chat-b",operation:"inspect",ok:false,error:{code:"not_found",commit_state:"not_committed"}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-b",reply)].phase,"unconfirmed","failed lookup does not prove the original send never committed");
  reply.text="Changed after submission";
  assert.equal(retryPeerRequest("chat-c",replyId),false);
  assert.equal(retryPeerRequest("chat-b",replyId),true);
  assert.equal(sent.at(-1)?.request_id,replyId,"explicit retry retains durable identity");
  assert.equal(sent.at(-1)?.text,"Found the cause","explicit retry cannot substitute edited content");
  assert.equal(retryPeerRequest("chat-b",replyId),false,"a retry cannot overlap itself through repeated clicks");
  ingestPeers({type:"peers:result",request_id:replyId,chat_id:"chat-b",operation:"reply",ok:false,error:{code:"validation",commit_state:"not_committed"}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-b",reply)].phase,"unconfirmed","a same-ID late failure cannot exclude another attempt's commit");
  ingestPeers({type:"peers:result",request_id:replyId,chat_id:"chat-b",operation:"reply",ok:true,result:message(replyId,{message_id:"reply-1",sender_peer_id:"opaque-peer-b",target_peer_id:"opaque-peer-a",in_reply_to:"opaque-message",content:"Found the cause",state:"unknown"})});
  assert.equal(getPeerState().requests[peerRequestKey("chat-b",reply)].result?.state,"unknown");
  const bad={operation:"send" as const,peer_id:"unavailable-peer",text:"Validation case"};
  const badId=requestPeer("chat-b",bad)!;
  ingestPeers({type:"peers:result",request_id:badId,chat_id:"chat-b",operation:"send",ok:false,error:{code:"invalid_target",commit_state:"not_committed"}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-b",bad)].phase,"rejected");
  assert.notEqual(requestPeer("chat-b",bad),badId,"a guaranteed noncommit permits a fresh user request");
  const draftKey=peerDraftKey("chat-a","opaque-peer-c");
  setPeerDraft(draftKey,"  Padded draft  ");
  const draftId=submitPeerDraft("chat-a",draftKey,{operation:"send",peer_id:"opaque-peer-c",text:"  Padded draft  "})!;
  setPeerConnection("offline");setPeerConnection("connected");
  setPeerDraft(draftKey,"Next message");
  const inboxId=requestPeer("chat-a",{operation:"inbox",direction:"all",limit:100})!;
  ingestPeers({type:"peers:result",request_id:inboxId,chat_id:"chat-a",operation:"inbox",ok:true,result:{peer_id:"opaque-peer-a",messages:[message(draftId,{message_id:"padded",target_peer_id:"opaque-peer-c",content:"Padded draft",revision:5})],cursor:1,revision:5}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-a",{operation:"send",peer_id:"opaque-peer-c",text:""})].phase,"accepted","canonical inbox reconciles uncertain sends");
  assert.equal(getPeerState().drafts[draftKey].text,"Next message","a late acknowledgement cannot erase a newer draft");
  const inspectId=requestPeer("chat-a",{operation:"inspect",message_id:"padded"})!;
  ingestPeers({type:"peers:result",request_id:inspectId,chat_id:"chat-a",operation:"inspect",ok:true,result:message(draftId,{message_id:"padded",target_peer_id:"opaque-peer-c",content:"Padded draft",state:"persisted",revision:2})});
  assert.equal(getPeerState().messages.padded.revision,5,"stale receipt cannot overwrite newer delivery evidence");
  const nextDraft=submitPeerDraft("chat-a",draftKey,{operation:"send",peer_id:"opaque-peer-c",text:"Next message"})!;
  ingestPeers({type:"peers:result",request_id:nextDraft,chat_id:"chat-a",operation:"send",ok:true,result:message(nextDraft,{message_id:"next",target_peer_id:"opaque-peer-c",content:"Next message"})});
  assert.equal(getPeerState().drafts[draftKey].text,"","matching receipt clears unchanged submitted draft");
  const launch=requestPeer("chat-a",{operation:"grok:launch"})!;
  setPeerConnection("offline");setPeerConnection("connected");
  const status=requestPeer("chat-a",{operation:"grok:status"})!;
  ingestPeers({type:"peers:result",request_id:status,chat_id:"chat-a",operation:"grok:status",ok:true,result:{items:[{request_id:launch,viewer_chat_id:"chat-b",owner_chat_id:"chat-a",binding_id:"foreign"}]}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-a",{operation:"grok:launch"})].phase,"unconfirmed");
  const status2=requestPeer("chat-a",{operation:"grok:status"})!;
  ingestPeers({type:"peers:result",request_id:status2,chat_id:"chat-a",operation:"grok:status",ok:true,result:{items:[{request_id:launch,viewer_chat_id:"chat-a",owner_chat_id:"chat-b",binding_id:"own"}]}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-a",{operation:"grok:launch"})].phase,"accepted");
  const permission=requestPeer("chat-a",{operation:"grok:permission",binding_id:"own",permission_id:"permission-1",option_id:"allow-once"})!;
  setPeerConnection("offline");const before=sent.length;setPeerConnection("connected");
  assert.equal(sent.length,before,"permission answer must not replay after reconnect");
  assert.equal(retryPeerRequest("chat-a",permission),false,"permission answers are excluded from retry helpers");
  assert.equal(requestPeer("chat-a",{operation:"grok:permission",binding_id:"own",permission_id:"permission-1",option_id:"deny"}),null,"uncertain permission cannot submit a contradictory answer");
  ingestPeers({type:"peers:grok:changed",chat_id:"chat-a",binding_id:"first",revision:9});
  ingestPeers({type:"peers:grok:changed",chat_id:"chat-a",binding_id:"second",revision:1});
  assert.equal(getPeerState().scopes["chat-a"].grokChanged,2,"binding-local revisions cannot suppress another binding's update");
  ingestPeers({type:"peers:grok:changed",chat_id:"chat-a",binding_id:"first",revision:8});
  assert.equal(getPeerState().scopes["chat-a"].grokChanged,2,"stale binding invalidation is ignored");
  assert.equal(parseGrokBinding({binding_id:"portable",viewer_chat_id:"chat-a",owner_chat_id:"chat-old",terminal_id:""},"chat-a")?.terminal_id,"");
  assert.equal(parseGrokBinding({binding_id:"portable",viewer_chat_id:"chat-other",owner_chat_id:"chat-a"},"chat-a"),null,"old launch ownership cannot override viewer correlation");
  assert.equal(parseGrokSavedSession({session_id:42}),null);
  assert.equal(grokDeliveryLabel("inbox",true).label,"Inbox only","connection flags cannot override declared inbox delivery");
  assert.equal(grokDeliveryLabel("agent_context_prompt",false).label,"Automatic wake unavailable");
  assert.match(grokDeliveryLabel("agent_context_prompt",true).detail,/user input/);
  const setup=requestPeer("chat-z",{operation:"grok:setup"})!;
  setPeerConnection("offline");setPeerConnection("connected");
  assert.equal(getPeerState().requests[peerRequestKey("chat-z",{operation:"grok:setup"})].phase,"unconfirmed");
  assert.equal(requestPeer("chat-z",{operation:"grok:setup"}),null,"ambiguous setup is not replayed");
  const setupStatus=requestPeer("chat-z",{operation:"grok:status"})!;
  ingestPeers({type:"peers:result",request_id:setupStatus,chat_id:"chat-z",operation:"grok:status",ok:true,result:{adapter:"grok-peer-bridge",installed:true,profile_id:"profile-one",installation_profile_id:"profile-one",items:[]}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-z",{operation:"grok:setup"})].phase,"accepted","current installed state reconciles convergent setup");
  assert.ok(setup);assert.equal(sent.filter(row=>row.chat_id==="chat-z" && row.type==="peers:grok:launch").length,0,"setup never launches a model or terminal");
  const sessions=requestPeer("chat-z",{operation:"grok:sessions"})!;
  setPeerConnection("offline");setPeerConnection("connected");
  assert.equal(getPeerState().requests[peerRequestKey("chat-z",{operation:"grok:sessions"})].phase,"rejected","saved-session reads are not ambiguous mutations");
  const freshSessions=requestPeer("chat-z",{operation:"grok:sessions"})!;assert.notEqual(freshSessions,sessions);
  ingestPeers({type:"peers:result",request_id:freshSessions,chat_id:"chat-z",operation:"grok:sessions",ok:true,result:{viewer_chat_id:"chat-z",items:[{session_id:"saved-one",title:"One",cwd:"D:/One"}],cursor:"opaque-next"}});
  const page=requestPeer("chat-z",{operation:"grok:sessions",cursor:"opaque-next"})!;
  const replacement=requestPeer("chat-z",{operation:"grok:sessions"})!;
  ingestPeers({type:"peers:result",request_id:page,chat_id:"chat-z",operation:"grok:sessions",ok:true,result:{viewer_chat_id:"chat-z",items:[{session_id:"stale-page"}],cursor:null}});
  assert.equal(getPeerState().grokSessions["chat-z"].items.some(row=>row.session_id==="stale-page"),false,"old pages cannot append into a refreshed list");
  ingestPeers({type:"peers:result",request_id:replacement,chat_id:"chat-z",operation:"grok:sessions",ok:true,result:{viewer_chat_id:"chat-z",items:[{session_id:"saved-new"}],cursor:null}});
  assert.deepEqual(getPeerState().grokSessions["chat-z"].items.map(row=>row.session_id),["saved-new"]);
  const resumed=requestPeer("chat-z",{operation:"grok:launch",session_id:"saved-new"})!;
  setPeerConnection("offline");setPeerConnection("connected");
  assert.equal(requestPeer("chat-z",{operation:"grok:launch",session_id:"different",cwd:"E:/Another"}),null,"changing saved-session selection cannot duplicate an uncertain launch");
  assert.equal(sent.find(row=>row.request_id===resumed)?.session_id,"saved-new");
  assert.equal("cwd" in sent.find(row=>row.request_id===resumed)!,false);
  ingestPeers({type:"peers:result",request_id:permission,chat_id:"chat-a",operation:"grok:permission",ok:true,result:{viewer_chat_id:"chat-other",permission_id:"permission-1",accepted:true}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-a",{operation:"grok:permission",binding_id:"own",permission_id:"permission-1",option_id:"once"})].phase,"unconfirmed","foreign viewer permission acknowledgment is rejected");
  const notice={operation:"send" as const,peer_id:"opaque-peer-b",text:"Status only",message_kind:"notice" as "request"|"notice"};
  const noticeId=requestPeer("chat-kind",notice)!;
  ingestPeers({type:"peers:result",request_id:noticeId,chat_id:"chat-kind",operation:"send",ok:true,result:message(noticeId,{message_id:"kind-message",content:"Status only",message_kind:"request"})});
  assert.equal(getPeerState().requests[peerRequestKey("chat-kind",notice)].phase,"unconfirmed","wrong message kind cannot acknowledge a notice as a work request");
  notice.message_kind="request";assert.equal(retryPeerRequest("chat-kind",noticeId),true);assert.equal(sent.at(-1)?.message_kind,"notice","retry keeps the originally committed kind");
  ingestPeers({type:"peers:result",request_id:noticeId,chat_id:"chat-kind",operation:"send",ok:true,result:message(noticeId,{message_id:"kind-message",content:"Status only",message_kind:"notice"})});
  assert.equal(getPeerState().requests[peerRequestKey("chat-kind",notice)].phase,"accepted");
  const delivery={operation:"grok:delivery" as const,peer_id:"grok:stock",delivery_mode:"inbox" as const,expected_delivery_mode:"agent_context_prompt" as const};
  const preferenceId=requestPeer("chat-mode",delivery)!;setPeerConnection("offline");const commandCount=sent.length;setPeerConnection("connected");assert.equal(sent.length,commandCount,"delivery changes do not replay on reconnect");
  assert.equal(requestPeer("chat-mode",{...delivery,delivery_mode:"agent_context_prompt"}),null);
  const refreshMode=requestPeer("chat-mode",{operation:"grok:status"})!;
  ingestPeers({type:"peers:result",request_id:refreshMode,chat_id:"chat-mode",operation:"grok:status",ok:true,result:{items:[{viewer_chat_id:"chat-mode",peer_id:"grok:stock",preferred_delivery_mode:"agent_context_prompt",delivery_mode:"inbox"}]}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-mode",delivery)].phase,"unconfirmed","effective inbox fallback cannot confirm a changed saved preference");
  const refreshPreference=requestPeer("chat-mode",{operation:"grok:status"})!;
  ingestPeers({type:"peers:result",request_id:refreshPreference,chat_id:"chat-mode",operation:"grok:status",ok:true,result:{items:[{viewer_chat_id:"chat-mode",peer_id:"grok:stock",preferred_delivery_mode:"inbox",delivery_mode:"inbox"}]}});
  assert.equal(getPeerState().requests[peerRequestKey("chat-mode",delivery)].phase,"accepted");assert.ok(preferenceId);
  disposePeers();
  console.log("Peer transport: explicit owner, correlated operation, duplicate guards, uncertain send retention, reconnect no-replay and stale reply isolation passed");
}
