import assert from "node:assert/strict";
import {act} from "react";
import {createRoot} from "react-dom/client";
import {AgentTeamPanel} from "../frontend/main-deck/src/chat/AgentTeamPanel";
import {refreshAgentTeam,selectTeamAgent} from "../frontend/main-deck/src/chat/agentTeam";
import {__resetChatStoreForTests} from "../frontend/main-deck/src/chatStore";
import {initialChatState,setChatState,setChatContext,getChatState,activateChatState,getCachedChatState} from "../frontend/main-deck/src/chat/stateCore";
import {ingestChat} from "../frontend/main-deck/src/chat/ingest";
import {parseChatWsMessage} from "../frontend/main-deck/src/protocol";
import {parseAgentDetail} from "../frontend/main-deck/src/protocol/children";
import {setChatConnection} from "../frontend/main-deck/src/chat/connection";
import {resetWireStatus} from "../frontend/main-deck/src/connectionUi";

export async function run() {
  __resetChatStoreForTests();resetWireStatus("chat");
  const sent:Array<Record<string,unknown>>=[];
  setChatContext({send:(value:Record<string,unknown>)=>{sent.push(value);return true;},isOpen:()=>true,notify(){}});
  setChatState({...initialChatState(),sessionId:"A",connected:true});
  const host=document.createElement("div"),root=createRoot(host);document.body.appendChild(host);
  const last=(type:string)=>sent.filter(row=>row.type===type).at(-1)!;
  const child=(id:string,parent:string|null=null)=>({child_id:id,parent_child_id:parent,parent_chat_id:parent?`chat-${parent}`:"A",child_chat_id:`chat-${id}`,name:id,task:`Assignment for ${id}`,status:"running",created_at:1700000000,started_at:1700000001,completed_at:null,run_generation:1,outcome:{status:id==="Beta"?"blocked":"unreported"},cleanup:null});
  const children=[child("Alpha"),child("Beta"),child("Gamma","Alpha")];
  const ingest=async(row:Record<string,unknown>)=>act(async()=>ingestChat(parseChatWsMessage(row)));
  const snapshot=(request:Record<string,unknown>,revision:number,rows=children)=>({type:"children:snapshot",schema:"variant1.children-snapshot.v1",session_id:"A",request_id:request.request_id,revision,total:rows.length,active:rows.length,blocked:1,truncated:false,children:rows});
  const detail=(request:Record<string,unknown>,id:string,revision=5,activity_revision=8)=>({type:"children:detail",schema:"variant1.child-detail.v1",session_id:"A",request_id:request.request_id,revision,activity_revision,child:{...child(id),report:`Report from ${id}`},activity_provenance:"canonical_work_operations",truncated:false,activity:[{operation_id:`op-${id}`,kind:"python.execute",status:"completed",created_at:1700000002,completed_at:1700000003,scope:{chat_id:`chat-${id}`,run_id:`run-${id}`}}]});
  try {
    await act(async()=>{root.render(<AgentTeamPanel/>);refreshAgentTeam();refreshAgentTeam();});
    assert.equal(sent.length,1,"roster reads coalesce");
    await ingest(snapshot(last("children:snapshot:get"),5));
    assert.equal(host.querySelectorAll('.agent-team__card').length,3);assert.ok(host.textContent?.includes("3 working · 1 blocked"));assert.ok(host.textContent?.includes("Assignment for Alpha"));assert.ok(host.textContent?.includes("Spawned"));assert.ok(host.textContent?.includes("From Alpha"));
    await act(async()=>host.querySelector<HTMLButtonElement>('[aria-label="Inspect Alpha"]')!.click());const alpha=last("children:detail:get");
    await act(async()=>selectTeamAgent("Beta"));const beta=last("children:detail:get");
    await ingest(detail(alpha,"Alpha"));assert.equal(getChatState().agentTeam.detail,null,"late selection response does not mix identities");
    await ingest(detail(beta,"Beta"));assert.ok(host.textContent?.includes("Beta · execution trace"));assert.ok(host.textContent?.includes("run-Beta"));assert.equal(host.textContent?.includes("Report from Alpha"),false);assert.ok(host.textContent?.includes("Report from Beta"));
    assert.equal(getChatState().messages.length,0,"child activity never enters parent transcript");assert.equal(getChatState().agentTeam.agents[0].cleanupStatus,"unknown");
    const beforeFlood=sent.length;
    await act(async()=>{
      for(let i=0;i<600;i++)ingestChat(parseChatWsMessage({type:"work:event",event:{type:["job.created","job.leased","job.started","job.succeeded"][i%4],aggregate:{kind:"job",id:`supervisor-${i}`,version:i+1},payload:{kind:i%3?"goal.supervise.v1":"artifact.render.v1"},scope:{chat_id:i%2?"A":"chat-Beta"}}}));
      ingestChat(parseChatWsMessage({type:"work:event",event:{aggregate:{kind:"job",id:"missing-kind",version:1},scope:{chat_id:"A"}}}));
    });
    assert.equal(sent.length,beforeFlood,"600 unrelated job events cause no roster or selected-detail traffic");
    await act(async()=>refreshAgentTeam());await ingest(snapshot(last("children:snapshot:get"),4,[]));assert.equal(getChatState().agentTeam.agents.length,3);
    await act(async()=>selectTeamAgent("Beta"));const olderActivity=last("children:detail:get");
    await ingest(detail(olderActivity,"Beta",6,7));assert.equal(getChatState().agentTeam.activityRevision,8,"child revision cannot overrule older operation clock");
    const invalid=detail(beta,"Beta");invalid.activity[0].scope.chat_id="wrong";assert.equal(parseAgentDetail(invalid),null);
    await ingest({type:"work:event",event:{aggregate:{kind:"operation",id:"op-Beta",version:9},scope:{chat_id:"chat-Beta"}}});const update=last("children:detail:get");
    await ingest({type:"work:event",event:{aggregate:{kind:"operation",id:"op-Beta",version:10},scope:{chat_id:"chat-Beta"}}});assert.equal(last("children:detail:get"),update);
    await ingest(detail(update,"Beta",6,9));assert.notEqual(last("children:detail:get").request_id,update.request_id,"one follow-up read captures events during load");
    await ingest(detail(last("children:detail:get"),"Beta",6,10));
    const rosterCount=sent.filter(row=>row.type==="children:snapshot:get").length;
    await ingest({type:"work:event",event:{aggregate:{kind:"job",id:"new-child-job",version:1},payload:{kind:"child.execute.v1"},scope:{chat_id:"A"}}});assert.equal(sent.filter(row=>row.type==="children:snapshot:get").length,rosterCount+1);
    const offscreen=last("children:snapshot:get");await act(async()=>activateChatState("B"));await ingest(snapshot(offscreen,7));assert.equal(getChatState().agentTeam.agents.length,0);assert.equal(getCachedChatState("A")?.agentTeam.revision,7);
    await act(async()=>activateChatState("A"));await act(async()=>refreshAgentTeam());const failed=last("children:snapshot:get");await ingest({type:"children:rejected",session_id:"A",request_id:failed.request_id,error:"Unavailable"});assert.equal(getChatState().agentTeam.agents.length,3);assert.ok(host.textContent?.includes("Unavailable"));
    // A real terminal child change during a detail read must not lose its follow-up.
    await act(async()=>selectTeamAgent("Beta"));const oldDetail=last("children:detail:get");
    const childEvent=(scope:string,type:string)=>({type:"work:event",event:{type,aggregate:{kind:"job",id:"actual-child-job",version:2},payload:{kind:"child.execute.v1"},scope:{chat_id:scope}}});
    await ingest(childEvent("A","job.succeeded"));
    const completed=children.map(row=>row.child_id==="Beta"?{...row,status:"completed",updated_at:1700000010}:row);
    await ingest(snapshot(last("children:snapshot:get"),8,completed));assert.equal(getChatState().agentTeam.detailDirty,true);
    await ingest(detail(oldDetail,"Beta",7,11));const newDetail=last("children:detail:get");assert.notEqual(newDetail.request_id,oldDetail.request_id);
    await ingest({...detail(newDetail,"Beta",8,12),child:{...completed[1],report:"New terminal report"}});
    assert.equal(getChatState().agentTeam.detail?.report,"New terminal report");assert.equal(getChatState().agentTeam.agents[1].status,"completed");
    // Child jobs scoped to a known child chat invalidate the root's nested tree.
    const beforeNested=sent.filter(row=>row.type==="children:snapshot:get").length;
    await ingest(childEvent("chat-Alpha","job.created"));const nestedRead=last("children:snapshot:get");
    assert.equal(sent.filter(row=>row.type==="children:snapshot:get").length,beforeNested+1);
    await ingest({type:"work:event",event:{aggregate:{kind:"job",id:"unrelated",version:9},payload:{kind:"goal.supervise.v1"},scope:{chat_id:"A"}}});
    assert.equal(getChatState().agentTeam.dirty,false,"irrelevant jobs cannot dirty an in-flight child read");
    await ingest(childEvent("chat-Alpha","job.started"));assert.equal(getChatState().agentTeam.dirty,true);
    await ingest(childEvent("unrelated-chat","job.succeeded"));
    await ingest(snapshot(nestedRead,9,completed));assert.equal(sent.filter(row=>row.type==="children:snapshot:get").length,beforeNested+2);
    await ingest(snapshot(last("children:snapshot:get"),10,completed));assert.equal(sent.filter(row=>row.type==="children:snapshot:get").length,beforeNested+2);
    const changed=(revision:number,session_id="A",child_id?:string)=>({type:"children:changed",schema:"variant1.children-changed.v1",session_id,revision,...(child_id?{child_id}:{})});
    const beforeChanges=sent.length;
    await ingest(changed(999,"unrelated-chat","Beta"));await ingest(changed(8,"A","Beta"));
    await ingest({...changed(11),schema:"wrong"});await ingest({...changed(11),revision:11.5});
    assert.equal(sent.length,beforeChanges,"unowned, stale and malformed invalidations do nothing");
    await ingest(changed(11,"A","Beta"));const changedRead=last("children:snapshot:get");
    const afterChangeRequest=sent.length;await ingest(changed(11,"A","Beta"));assert.equal(sent.length,afterChangeRequest,"duplicate child-clock notification coalesces");
    await ingest(changed(12,"A","Beta"));assert.equal(getChatState().agentTeam.detailDirty,true);
    const detailsBeforeChange=sent.filter(row=>row.type==="children:detail:get").length;
    await ingest(snapshot(changedRead,12,completed));
    assert.equal(sent.filter(row=>row.type==="children:detail:get").length,detailsBeforeChange+1,"targeted non-job change refreshes detail even when roster fields are identical");
    await ingest(snapshot(last("children:snapshot:get"),12,completed));
    await ingest({...detail(last("children:detail:get"),"Beta",12,13),child:{...completed[1],report:"Non-job change report"}});
    assert.equal(getChatState().agentTeam.detail?.report,"Non-job change report");
    await act(async()=>selectTeamAgent("Gamma"));const deletingDetail=last("children:detail:get");
    await ingest(changed(13,"chat-Alpha","Gamma"));
    await ingest(snapshot(last("children:snapshot:get"),13,completed.filter(row=>row.child_id!=="Gamma")));
    assert.equal(getChatState().agentTeam.selectedId,null,"nested deletion closes the removed child's detail");
    await ingest({...detail(deletingDetail,"Gamma",12,14),child:{...child("Gamma","Alpha"),report:"Late deleted child"}});
    assert.equal(getChatState().agentTeam.detail,null,"late deleted-child reply cannot restore its projection");
    const afterDelete=sent.length;await ingest(changed(12,"A"));assert.equal(sent.length,afterDelete);
    await act(async()=>refreshAgentTeam(true));assert.equal(sent.length,afterDelete+1,"manual refresh remains available independently of event revision");
    await ingest(snapshot(last("children:snapshot:get"),13,completed.filter(row=>row.child_id!=="Gamma")));
    await act(async()=>selectTeamAgent("Beta"));const beforeDisconnect=last("children:detail:get");
    await act(async()=>setChatConnection("offline"));
    await act(async()=>{setChatConnection("connected");await new Promise(resolve=>setTimeout(resolve,230));});
    const reconnectRead=sent.filter(row=>row.type==="children:snapshot:get" && row.session_id==="A").at(-1)!;
    await ingest(snapshot(reconnectRead,13,completed.filter(row=>row.child_id!=="Gamma")));
    const reconnectDetail=last("children:detail:get");assert.notEqual(reconnectDetail.request_id,beforeDisconnect.request_id);
    await ingest({...detail(beforeDisconnect,"Beta",13,14),child:{...completed[1],report:"Obsolete pre-disconnect report"}});
    assert.notEqual(getChatState().agentTeam.detail?.report,"Obsolete pre-disconnect report");
    await ingest({...detail(reconnectDetail,"Beta",13,15),child:{...completed[1],report:"Reconnected report"}});
    assert.equal(getChatState().agentTeam.detail?.report,"Reconnected report");assert.equal(getChatState().agentTeam.synced,true);
    // Post-commit notifications from different worker threads can arrive out of order.
    const stableRows=completed.filter(row=>row.child_id!=="Gamma");
    await act(async()=>refreshAgentTeam(true));await ingest(snapshot(last("children:snapshot:get"),51,stableRows));
    const beforeReorderRoster=sent.filter(row=>row.type==="children:snapshot:get").length;
    const beforeReorderDetail=sent.filter(row=>row.type==="children:detail:get").length;
    await ingest(changed(53,"A","Alpha"));const reorderRead=last("children:snapshot:get");
    await ingest(changed(52,"A","Beta"));await ingest(changed(53,"A","Alpha"));
    assert.equal(sent.filter(row=>row.type==="children:snapshot:get").length,beforeReorderRoster+1);
    assert.equal(getChatState().agentTeam.detailDirty,true,"new global clock covers earlier selected-child changes even when a different child notified first");
    await ingest(snapshot(reorderRead,53,stableRows));
    assert.equal(sent.filter(row=>row.type==="children:detail:get").length,beforeReorderDetail+1,"unchanged roster fields cannot hide a reordered message-only update");
    await ingest({...detail(last("children:detail:get"),"Beta",53,16),child:{...completed[1],report:"Reordered message-only report"}});
    assert.equal(getChatState().agentTeam.detail?.report,"Reordered message-only report");
    const afterReorder=sent.length;await ingest(changed(52,"A","Beta"));await ingest(changed(53,"A","Alpha"));
    assert.equal(sent.length,afterReorder,"reordered duplicates do not create a read loop");
    // A snapshot can beat the post-commit notification too; roster coverage is
    // not sufficient for a message-only detail update.
    await act(async()=>refreshAgentTeam(true));await ingest(snapshot(last("children:snapshot:get"),60,stableRows));
    const beforeCovered=sent.length;
    await ingest(changed(60,"A","Alpha"));const coveredDetail=last("children:detail:get");
    assert.equal(sent.length,beforeCovered+1);assert.equal(sent.at(-1)?.type,"children:detail:get","already-covered roster does not refetch, but stale detail does");
    await ingest(changed(59,"A","Beta"));assert.equal(sent.length,beforeCovered+1);
    await ingest({...detail(coveredDetail,"Beta",60,17),child:{...completed[1],report:"Snapshot-first message report"}});
    assert.equal(getChatState().agentTeam.detail?.report,"Snapshot-first message report");
  } finally {await act(async()=>root.unmount());host.remove();resetWireStatus("chat");}
  console.log("Agent team: scoped roster, nested identity, spawn/task visibility, isolated traces, independent revisions, event coalescing and offscreen preservation passed");
}
