import assert from "node:assert/strict";
import {act} from "react";
import {createRoot} from "react-dom/client";
import {ProviderRoutingSettings} from "../frontend/main-deck/src/ProviderRoutingSettings";
import {ExternalContextSettings} from "../frontend/main-deck/src/ExternalContextSettings";
import * as routing from "../frontend/main-deck/src/providerRoutingStore";
import * as context from "../frontend/main-deck/src/externalContextSettingsStore";
import {setSessionContext,setSessionConnection,ingestSessions} from "../frontend/main-deck/src/state/sessionStore";
import {getAppState,navigateTo} from "../frontend/main-deck/src/state/appStore";
import type {RuntimeContext} from "../frontend/main-deck/src/types";
const pause=()=>new Promise(resolve=>setTimeout(resolve,0));

export async function run(){
  const sent:Array<Record<string,unknown>>=[];
  const runtime={send:(command:Record<string,unknown>)=>{sent.push(command);return true;},isOpen:()=>true,notify:()=>{}} as unknown as RuntimeContext;
  const host=document.createElement('div');document.body.appendChild(host);const root=createRoot(host);
  const last=(type:string,operation?:string)=>sent.filter(row=>row.type===type && (!operation || row.operation===operation)).at(-1)!;
  const replyRouting=(request:Record<string,unknown>,result:unknown,ok=true)=>routing.ingestProviderRouting({type:'provider-recovery:result',operation:String(request.type).split(':')[1],request_id:request.request_id,ok,result,error:{code:'test',message:'Saved settings changed.'}});
  const replyContext=(request:Record<string,unknown>,result:unknown,ok=true)=>context.ingestExternalContextSettings({type:'external-context:result',operation:request.operation,request_id:request.request_id,chat_id:request.chat_id,ok,result,error:{code:'test',message:'Retained source unavailable.'}});
  const button=(text:string)=>[...host.querySelectorAll<HTMLButtonElement>('button')].find(row=>row.textContent===text)!;
  const config=routing.defaultRecovery();
  routing.setProviderRoutingContext(runtime);context.setExternalContextSettingsContext(runtime);setSessionContext(runtime);
  await act(async()=>{routing.setProviderRoutingConnection('connected');context.setExternalContextSettingsConnection('connected');setSessionConnection('connected');ingestSessions({type:'chat:sessions',active_id:'chat-a',items:[{id:'chat-a',title:'First session'},{id:'chat-b',title:'Second session'}]});root.render(<ProviderRoutingSettings/>);});
  try{
    await act(async()=>replyRouting(last('provider-recovery:get'),{config,revision:'r1'}));
    assert.equal(host.querySelector('[aria-label="Enable configured recovery"]')?.getAttribute('aria-checked'),'false','recovery defaults off');
    const draft={...config,enabled:true,fallback_routes:[{mode:'cloud' as const,provider:'fixture',model:'one'},{mode:'local' as const,provider:'local',model:'two'}]};
    await act(async()=>routing.editProviderRouting(draft));
    await act(async()=>host.querySelector<HTMLButtonElement>('[aria-label="Move Main backups route 2 earlier"]')!.click());
    assert.equal(routing.getProviderRouting().draft.fallback_routes[0].model,'two','route order is meaningful');
    await act(async()=>button('Save routing').click());const save=last('provider-recovery:set');assert.equal(save.expected_revision,'r1');
    assert.doesNotMatch(host.textContent!,/settings saved/,'a click does not imply saved');
    await act(async()=>replyRouting(save,null,false));assert.equal(routing.getProviderRouting().dirty,true,'rejected save keeps draft');
    await act(async()=>{routing.setProviderRoutingConnection('offline');});assert.equal(routing.getProviderRouting().draft.enabled,true,'disconnect keeps draft');
    await act(async()=>routing.setProviderRoutingConnection('connected'));
    await act(async()=>replyRouting(last('provider-recovery:get'),{config,revision:'r2'}));
    const beforeSave=sent.length;await act(async()=>routing.saveProviderRouting());assert.equal(sent.length,beforeSave,'new revision cannot silently overwrite a stale draft');
    await act(async()=>routing.revertProviderRouting());
    await act(async()=>{routing.editProviderRouting({...config,max_attempts:13});routing.saveProviderRouting();});assert.match(routing.getProviderRouting().error,/1 to 12/);
    await act(async()=>{routing.editProviderRouting(draft);routing.saveProviderRouting();});const accepted=last('provider-recovery:set');
    await act(async()=>replyRouting(accepted,{config:draft,revision:'r3'}));assert.match(host.textContent!,/Routing settings saved/);
    await act(async()=>root.render(<ExternalContextSettings/>));
    await act(async()=>context.chooseContextChat('chat-a'));const oldViews=last('external-context:request','views');
    await act(async()=>context.chooseContextChat('chat-b'));
    await act(async()=>replyContext(oldViews,{items:[{view_id:'wrong-view'}]}));assert.equal(context.getExternalContextSettings().views.length,0,'late old-session views ignored');
    await act(async()=>replyContext(last('external-context:request','views'),{items:[{view_id:'view-b',created_at:'2026-10-03'}],has_more:false,next_cursor:null}));
    await act(async()=>context.chooseContextView('view-b'));
    await act(async()=>{replyContext(last('external-context:request','status'),{view_id:'view-b',counts:{message:2,cell:1,snapshot:1},coverage:{snapshots:'metadata only'}});replyContext(last('external-context:request','read'),{view_id:'view-b',items:[{source_id:'one',kind:'cell',ordinal:1,preview:'value = 1'}],has_more:true,next_cursor:41});});
    await act(async()=>context.turnContextPage(true));assert.equal(last('external-context:request','read').after,41);
    await act(async()=>replyContext(last('external-context:request','read'),{view_id:'view-b',items:[{source_id:'two',kind:'message',ordinal:41,preview:'later'}],has_more:false,next_cursor:null}));
    assert.equal(context.getExternalContextSettings().items.length,1,'only current source page retained');
    await act(async()=>context.expandContextSource('two'));const oldDetail=last('external-context:request','expand');
    await act(async()=>context.expandContextSource('three'));
    await act(async()=>replyContext(oldDetail,{view_id:'view-b',source:{source_id:'two'},text:'stale text',offset:0,total_chars:10}));assert.equal(context.getExternalContextSettings().detail,null);
    await act(async()=>replyContext(last('external-context:request','expand'),{view_id:'view-b',source:{source_id:'three'},text:'😀'.repeat(12000),offset:0,has_more:true,next_offset:12000,total_chars:24000}));assert.equal(context.getExternalContextSettings().detail?.text.length,24000,'bounded Unicode source chunks are not mistaken for oversized UTF-16');
    await act(async()=>context.turnContextDetail(true));assert.equal(last('external-context:request','expand').offset,12000);
    await act(async()=>replyContext(last('external-context:request','expand'),{view_id:'view-b',source:{source_id:'three'},text:'<script>unsafe()</script>',offset:12000,has_more:false,next_offset:null,total_chars:24000}));assert.equal(host.querySelector('script'),null,'evidence stays inert text');
    const priorApi=window.variant1Deck;window.variant1Deck={chooseContextExportPath:async()=>({ok:true,cancelled:true})};
    const count=sent.filter(row=>row.operation==='export').length;
    await act(async()=>{button('Export view').click();await pause();});assert.equal(sent.filter(row=>row.operation==='export').length,count,'cancelled save dialog creates no export');
    window.variant1Deck={chooseContextExportPath:async()=>({ok:true,cancelled:false,path:'C:\\fixture\\export.jsonl',overwrite:false})};
    await act(async()=>{button('Export view').click();await pause();});const exportRequest=last('external-context:request','export');assert.equal(exportRequest.view_id,'view-b');assert.doesNotMatch(host.textContent!,/Context export saved/);
    await act(async()=>replyContext(exportRequest,null,false));assert.doesNotMatch(host.textContent!,/Context export saved/);
    await act(async()=>{button('Export view').click();await pause();});
    await act(async()=>replyContext(last('external-context:request','export'),{view_id:'view-b',path:'C:\\fixture\\export.jsonl',bytes:123,source_count:3,omission_count:1}));assert.match(host.textContent!,/123 bytes.*3 sources.*1 omissions/);
    window.variant1Deck=priorApi;
    await act(async()=>context.ingestExternalContextSettings({type:'chat:session:deleted',id:'chat-b'}));assert.equal(context.getExternalContextSettings().viewId,'','deletion releases evidence display');
    await act(async()=>context.chooseContextChat('chat-a'));
    const sourceParentViews=last('external-context:request','views');
    await act(async()=>replyContext(last('external-context:request','children'),{items:[{child_id:'goal-child',name:'Goal worker',status:'completed'}],truncated:true}));
    assert.equal(context.getExternalContextSettings().children[0].child_id,'goal-child');
    await act(async()=>context.chooseContextChild('goal-child'));
    assert.equal(last('external-context:request','views').child_id,'goal-child','saved views are explicitly child scoped');
    await act(async()=>replyContext(sourceParentViews,{items:[{view_id:'wrong-parent-view'}],has_more:false}));
    assert.equal(context.getExternalContextSettings().views.length,0,'late parent views do not enter child selection');
    await act(async()=>context.captureContext());
    assert.equal(last('external-context:request','capture').child_id,'goal-child','child capture keeps the parent reader scope');
    navigateTo('memory');assert.equal(getAppState().settingsCategory,'session-context','old Memory deep link opens context browser');
    console.log('Context/routing Settings: bounded reads, source identity/Unicode, stale replies, deletion, cancel/export receipts, ordered chains, revision conflicts, failed-save and reconnect drafts passed');
  }finally{
    await act(async()=>{root.unmount();routing.setProviderRoutingConnection('offline');context.setExternalContextSettingsConnection('offline');setSessionConnection('offline');});host.remove();
  }
}
